import type { DeepWiden } from "../types";
import type { appRoutesDe } from "../de/appRoutes";

export const appRoutesEn = {
  restoring: "Restoring your session …",
  checkingOperator: "Checking operator access …",
  operatorTitle: "Operators only.",
  operatorDetail: "You can use the Scout with your account. The operator view is available to authorized accounts.",
  scout: "Go to Scout",
  errorTitle: "This view could not be loaded.",
  errorDetail: "Try again. Your saved data is still here.",
  reload: "Reload",
  home: "Back to home",
  profileMenu: "Profile menu",
  settings: "Settings",
  messages: "Messages",
  operator: "Operator view",
  signOut: "Sign out",
  signOutError: "Signing out did not work. Please try again.",
  workspace: {
    home: "RoomScout home",
    account: "Your account",
    accountNavigation: "RoomScout and account",
    personalScout: "Your personal Scout",
    scout: "Scout",
    explore: "Explore listings",
    search: "Your search",
    map: "Map",
  },
  auth: {
    personalScout: "Your personal RoomScout",
    signUpTitle: "Your next rehearsal room starts here.",
    signUpSubtitle: "One conversation. One search. Your Scout stays on it.",
    signInTitle: "Welcome back.",
    signInSubtitle: "Your search and conversations are waiting for you.",
  },
  onboarding: {
    eyebrow: "Your musician profile",
    title: "Who does your Scout represent?",
    lead: "RoomScout uses this short introduction when contacting providers. You can discuss music and room needs with the Scout next.",
    firstName: "First name",
    firstNamePlaceholder: "Alex",
    lastName: "Last name (optional)",
    lastNamePlaceholder: "Not shared automatically",
    lastNameHint: "Your last name stays out of provider inquiries.",
    actKind: "You are searching for …",
    band: "A band",
    bandDescription: "A band name is optional.",
    solo: "A solo project",
    soloDescription: "Use an artist name or simply your first name.",
    actName: "Band or artist name (optional)",
    actNamePlaceholder: "Neon Harbour",
    preview: "How providers will see you",
    previewHint: "RoomScout uses this exact sender name. Your login username is not shared.",
    save: "Confirm profile",
    update: "Save profile",
    loading: "Loading your profile …",
    error: "Your profile could not be saved. Check your details and try again.",
  },
} as const satisfies DeepWiden<typeof appRoutesDe>;
