import type { DeepWiden } from "../types";
import type { liveInboxDe } from "../de/liveInbox";

export const liveInboxEn = {
  title: "Messages",
  navAria: "Messages",
  messagesAria: "Message history",
  scrollToEnd: "Jump to the newest messages",
  count: { one: "{count} conversation", other: "{count} conversations" },
  loading: "Loading your conversations …",
  threadLoading: "Loading the conversation …",
  notFound: "This conversation no longer exists.",
  empty: "No conversations yet. They will appear here once your Scout contacts a provider.",
  emptyAction: "Go to Scout",
  emptyThread: "Your Scout is preparing the first message.",
  selectHint: "Choose a conversation on the left.",
  provider: "Provider",
  scout: "Your Scout",
  you: "You",
  youToScout: "You to your Scout",
  previewProvider: "Provider: {text}",
  previewScout: "Your Scout: {text}",
  previewYou: "You: {text}",
  unread: "New message",
  stateOfferReady: "Offer ready",
  stateThinking: "Scout is reviewing",
  channelPortal: "Portal",
  channelMail: "Email",
  channelNone: "No channel yet",
  subtitle: "{city} · {label}",
  subtitleChannelOnly: "{label}",
  scoutNote: "Your Scout: {text}",
  scoutNoteNext: "Next step: {text}",
  decisionAnswered: "Decision: {label} → {text}",
  decisionAnsweredUnknown: "answered",
  pendingSending: "Sending …",
  pendingApproval: "Waiting for your approval",
  pendingApprovalAction: "Open decision",
  pendingAcceptance: "Acceptance is waiting for your approval",
  pendingAcceptanceAction: "Review acceptance",
  pendingFailed: "Could not be sent.",
  pendingBlocked: "Your Scout cannot send this right now.",
  pendingDrafted: "Your Scout is preparing the message.",
  composerPlaceholder: "Message the provider …",
  composerSend: "Send",
  composerSending: "Handing off your message …",
  composerStatus: "Conversation status",
  composerRestore: "Restore failed draft",
  hintThinking: "Your Scout is reviewing the latest reply …",
  hintClosed: "This conversation has ended.",
  hintChannelNotReady: "The provider cannot be reached right now.",
  hintAssessmentRequired: "Your Scout is still reviewing the latest reply.",
  errorNotFound: "This conversation no longer exists.",
  errorClosed: "This conversation has ended.",
  errorAssessmentRequired: "Your Scout is still reviewing the latest reply. You can write again in a moment.",
  errorContextChanged: "The search changed. Your Scout is reviewing the conversation again.",
  errorChannelNotReady: "The provider cannot be reached right now.",
  errorInvalidBody: "This message cannot be sent as written.",
  errorGeneric: "That did not work. Please try again.",
} as const satisfies DeepWiden<typeof liveInboxDe>;
