import type { DeepWiden } from "../types";
import type { liveSettingsCopy } from "../../settings/liveCopy";

export const liveSettingsEn = {
  autoSourcesFixed: "Automatic source selection is currently always on. You can exclude individual sources below.",
  noSourcesYet: "No sources configured for this search yet.",
  noMoreSources: "No additional portal connections are currently available.",
  connectionScope: "Manage portal access for messages and replies here. Source selection for this search remains separate.",
  saved: "Saved.",
  actionFailed: "The action could not be completed.",
  synced: "Portal inbox synchronized.",
  registrationStarted: "Secure Scout registration started.",
  authenticationStarted: "Secure sign-in started.",
  connectionAdded: "Portal connection added.",
  connectionPaused: "Portal connection paused.",
  connectionRemoved: "Portal connection and browser context removed.",
  mailboxReady: "Scout address is ready.",
  personalArea: "Personal workspace",
  discardTitle: "Unsaved changes",
  discardDescription: "Your changes have not been saved yet.",
  keepEditing: "Keep editing",
  discard: "Discard",
  discardBody: "Your changes will be lost when you leave.",
  removeTitle: "Remove portal connection?",
  removeDescription: "The saved browser context will be deleted; the provider account will remain.",
  keepConnected: "Keep connected",
  removeConnection: "Remove connection",
  removeBody: "Your Scout will no longer use this portal.",
  sourcesTitle: "Sources & access",
  sourcesForCity: "Sources for your search in {city}.",
  sourcesNoNeed: "Create a search with your Scout first.",
  includeSource: "Include {name}",
  portalConnections: "Portal connections",
  portalStatusActive: "Active",
  portalStatusNeedsAuth: "Sign-in required",
  portalStatusReauthRequired: "Sign in again",
  portalStatusPaused: "Paused",
  portalStatusDisabled: "Disabled",
  portalStatusUnknown: "Unknown status",
  portalPolicyAllowed: "Approved for use",
  portalPolicyBlocked: "Not approved for use",
  portalPolicyUnknown: "Approval unresolved",
  syncInbox: "Sync inbox",
  pause: "Pause",
  authenticate: "Sign in securely",
  registerScout: "Register Scout",
  recoverFirecrawlProfile: "Check saved profile",
  viewRegistrationProgress: "View progress",
  firecrawlManualLoginUnsupported: "Manual sign-in for Firecrawl is not available here.",
  registrationQueued: "Registration queued",
  registrationOpening: "Opening registration",
  registrationWaitingVerification: "Waiting for verification email",
  registrationSubmittingVerification: "Checking verification code",
  registrationFailed: "Registration failed",
  remove: "Remove",
  include: "Include",
  scoutAddress: "Scout address",
  notConfigured: "Not configured yet",
  configureAddress: "Set up address",
  autonomyTitle: "Autonomy",
  autonomyLead: "Saved permissions for the current search.",
  createNeedFirst: "Create a search with your Scout first.",
  mandateSummary: "Version {version} · until {date} · up to {count} contacts per day.",
  commitmentBoundary: "Binding decisions, bookings, and payments still require your exact approval.",
  pauseAutopilot: "Pause Autopilot",
  reviewMode: "Review every action",
  reviewModeBody: "Your Scout researches only after your explicit approval. Standard Autopilot permits only non-binding actions within fixed limits.",
  activateAutopilot: "Turn on standard Autopilot",
  modeGuided: "Review every action",
  modeResearch: "Research Autopilot",
  modeOutreach: "Outreach Autopilot",
  modeNegotiation: "Negotiation Autopilot",
  autonomySaveFailed: "Autonomy settings could not be saved.",
  knowledgeTitle: "What your Scout knows",
  noContext: "No summarized context yet.",
  knowledgeCategoriesAria: "Knowledge categories",
  knowledgeEmpty: "I haven't saved anything here yet.",
  knowledgeNoChanges: "No changes yet.",
  knowledgeSourceConversation: "From the conversation",
  knowledgeSourceImport: "From imported context",
  knowledgeSourceUserEdit: "Edited by you",
  knowledgeSourceAgentMail: "From a Scout message",
  knowledgeSourceObserved: "Observed by your Scout",
  knowledgeSourceSavedNeed: "Part of your current search",
  knowledgeSavedNeedSubject: "Your search",
  knowledgeNoSharing: "No room sharing",
  knowledgeSharingOpen: "Open to sharing a room",
  knowledgePeople: "{count} people",
  knowledgeGenreJoiner: " and ",
  knowledgeRadius: "{count} km radius",
  knowledgeBudget: "Up to €{value} / month",
  knowledgeLoudPaRequirement: "Loud rehearsals with a PA required",
  importContext: "Import context",
  retireFact: "Stop using",
  changeLog: "Change history",
  profileTitle: "Profile",
  profileLead: "Choose who your Scout represents and how RoomScout introduces you to providers.",
  displayName: "Display name",
  save: "Save",
  immutableLogin: "Username and sign-in remain unchanged: {username}",
  notificationsTitle: "Notifications",
  openInbox: "Open inbox",
  billingTitle: "Plan & usage",
  privacyTitle: "Privacy",
  privacyLead: "RoomScout stores searches, reviewed memories, approvals, and event metadata in Convex.",
  notStored: "Raw audio, passwords, 2FA values, cookies, and short-lived Live View links are not stored.",
  loading: "Loading settings …",
  unavailable: "This setting is not connected to a reliable service yet.",
  sourceDisclosure: "Sources apply only to the selected search. Excluded sources are not used.",
  notificationUnavailable: "Notifications currently appear only in RoomScout. Email, push, and browser settings are not available yet.",
  billingUnavailable: "RoomScout currently has no plan, billing data, or reliable user-level usage totals.",
  billingAccess: "Your access",
  billingDemoAccess: "Demo access",
  billingNoSubscription: "No paid subscription is active.",
  billingViewPlans: "View plans",
  billingActivity: "Activity",
  billingNotTracked: "Not tracked yet",
  billingActiveSearches: "Active searches",
  billingProvidersContacted: "Providers contacted",
  billingScoutConversations: "Conversations with Scout",
  billingActivityFootnote: "Activity overview, not billing units.",
  billingPaymentTitle: "Payment details",
  billingPaymentDetail: "No payment method saved",
  billingManage: "Manage",
  billingAddressTitle: "Billing address",
  billingAddressDetail: "Not provided yet",
  billingAdd: "Add",
  billingInvoices: "Invoices",
  billingNoInvoices: "No invoices yet",
  billingReceiptsLater: "Your receipts will appear here later.",
  billingNoIntegration: "No payment integration yet",
  privacyUnavailable: "Data export and account deletion are not yet available as secure self-service actions.",
  privacyDataTitle: "Your data, your control",
  privacyDataLead: "See what RoomScout stores in the cloud for your search and where you can manage it.",
  privacyStoredTitle: "Saved details",
  privacyStoredFallback: "Details about your band and search",
  privacyStoredOne: "{count} detail about you and your search",
  privacyStoredMany: "{count} details about you and your search",
  privacyViewStored: "View saved details",
  privacyTranscriptTitle: "Conversation history",
  privacyTranscriptDetail: "Your conversations with the Scout are available in the app.",
  privacyViewTranscript: "View conversations",
  privacyPortalsTitle: "Portal connections",
  privacyPortalsFallback: "Connections to your portals",
  privacyPortalsOne: "{count} connected portal account",
  privacyPortalsMany: "{count} connected portal accounts",
  privacyManagePortals: "Manage portal connections",
  privacyExportTitle: "Export",
  privacyExportDetail: "Secure self-service data export is not available yet.",
  privacyExport: "Export data",
  privacyDeleteTitle: "Delete account",
  privacyDeleteDetail: "Permanent deletion of all account data is not yet available as a secure self-service action.",
  privacyDelete: "Delete account",
  privacyVendorsTitle: "Service providers",
  privacyVendorsDetail: "Depending on the feature, RoomScout uses Convex, OpenAI, Firecrawl, AgentMail, and Browserbase for data storage, AI processing, web research, Scout inboxes, and portal access.",
  importDialogTitle: "Import your music context",
  importCollectDescription: "Bring useful context. Keep control.",
  importReviewDescription: { one: "1 of {n} selected", other: "{count} of {n} selected" },
  importAnalyze: "Analyze for review",
  importBack: "Back",
  importRemember: { one: "Remember 1 fact", other: "Remember {count} facts" },
  importStepAsk: "01 · Ask your current assistant",
  importAskBody: "Copy this prompt into ChatGPT, Claude, or another assistant that already knows your music life.",
  importPrompt: "I am setting up RoomScout, an assistant that helps musicians and bands find rehearsal rooms and compatible room-sharing partners. Based only on things I have explicitly told you in our previous conversations, create a concise context export about my music life. Include useful facts about bands, projects, members, roles, instruments, genres, working style, rehearsals, schedules, locations, mobility, equipment, storage, noise, access, budget, room preferences, deal-breakers, openness to sharing, current goals, and unresolved questions. Keep distinctions between me, other people, and bands clear. Mark uncertain or outdated information as uncertain. Do not guess. Do not include passwords, authentication details, financial account data, health information, exact home addresses, private contact details, or unrelated personal information. Return plain text with clear headings and bullet points. I will review the result before RoomScout stores any extracted facts.",
  importCopyPrompt: "Copy prompt",
  importCopied: "Copied",
  importStepPaste: "02 · Paste the result here",
  importPasteBody: "RoomScout extracts candidate details with the AI Gateway. Nothing is stored until you review and confirm them.",
  importSourceLabel: "External assistant context",
  importSourcePlaceholder: "Paste your music context export…",
  importScoutReadout: "Scout readout",
  importReviewMeta: { one: "Candidates: 1 · entities: {n} · no raw export stored", other: "Candidates: {count} · entities: {n} · no raw export stored" },
  importCategoryIdentity: "Identity",
  importCategoryMusic: "Music",
  importCategoryLocation: "Location",
  importCategoryMobility: "Mobility",
  importCategorySchedule: "Schedule",
  importCategoryEquipment: "Equipment",
  importCategoryGoal: "Goal",
  importCategoryPreference: "Preference",
  importCategoryConstraint: "Constraint",
  importCategoryRelationship: "Relationship",
  importCategoryCollaboration: "Collaboration",
  importCategoryRoomNeed: "Room need",
  importCategoryOther: "Other",
  importSensitivityPersonal: "personal",
  importSensitivitySensitive: "sensitive",
  importError: "The context could not be processed. Please try again.",
} as const satisfies DeepWiden<typeof liveSettingsCopy>;
