import type { DeepWiden } from "../types";
import type { liveSettingsCopy } from "../../settings/liveCopy";

export const liveSettingsEn = {
  autoSourcesFixed: "Automatic source selection is currently always on. You can exclude individual sources below.",
  noSourcesYet: "No sources configured for this search yet.",
  noMoreSources: "No additional portal connections are currently available.",
  connectionScope: "Manage portal access for messages and replies here. Source selection for this search remains separate.",
  saved: "Saved.",
  actionFailed: "The action could not be completed.",
  synced: "Portal inbox synchronized.",
  registrationStarted: "Secure Scout registration started.",
  authenticationStarted: "Secure sign-in started.",
  connectionAdded: "Portal connection added.",
  connectionPaused: "Portal connection paused.",
  connectionRemoved: "Portal connection and browser context removed.",
  mailboxReady: "Scout address is ready.",
  personalArea: "Personal workspace",
  discardTitle: "Unsaved changes",
  discardDescription: "Your changes have not been saved yet.",
  keepEditing: "Keep editing",
  discard: "Discard",
  discardBody: "Your changes will be lost when you leave.",
  removeTitle: "Remove portal connection?",
  removeDescription: "The saved browser context will be deleted; the provider account will remain.",
  keepConnected: "Keep connected",
  removeConnection: "Remove connection",
  removeBody: "Your Scout will no longer use this portal.",
  sourcesTitle: "Sources & access",
  sourcesForCity: "Sources for your search in {city}.",
  sourcesNoNeed: "Create a search with your Scout first.",
  includeSource: "Include {name}",
  portalConnections: "Portal connections",
  portalStatusActive: "Active",
  portalStatusNeedsAuth: "Sign-in required",
  portalStatusReauthRequired: "Sign in again",
  portalStatusPaused: "Paused",
  portalStatusDisabled: "Disabled",
  portalStatusUnknown: "Unknown status",
  portalPolicyAllowed: "Approved for use",
  portalPolicyBlocked: "Not approved for use",
  portalPolicyUnknown: "Approval unresolved",
  syncInbox: "Sync inbox",
  pause: "Pause",
  authenticate: "Sign in securely",
  registerScout: "Register Scout",
  recoverFirecrawlProfile: "Check saved profile",
  viewRegistrationProgress: "View progress",
  firecrawlManualLoginUnsupported: "Manual sign-in for Firecrawl is not available here.",
  registrationQueued: "Registration queued",
  registrationOpening: "Opening registration",
  registrationWaitingVerification: "Waiting for verification email",
  registrationSubmittingVerification: "Checking verification code",
  registrationFailed: "Registration failed",
  remove: "Remove",
  include: "Include",
  scoutAddress: "Scout address",
  notConfigured: "Not configured yet",
  configureAddress: "Set up address",
  autonomyTitle: "Autonomy",
  autonomyLead: "Saved permissions for the current search.",
  createNeedFirst: "Create a search with your Scout first.",
  mandateSummary: "Version {version} · until {date} · up to {count} contacts per day.",
  commitmentBoundary: "Binding decisions, bookings, and payments still require your exact approval.",
  pauseAutopilot: "Pause Autopilot",
  reviewMode: "Review every action",
  reviewModeBody: "Your Scout researches only after your explicit approval. Standard Autopilot permits only non-binding actions within fixed limits.",
  activateAutopilot: "Turn on standard Autopilot",
  modeGuided: "Review every action",
  modeResearch: "Research Autopilot",
  modeOutreach: "Outreach Autopilot",
  modeNegotiation: "Negotiation Autopilot",
  autonomySaveFailed: "Autonomy settings could not be saved.",
  knowledgeTitle: "What your Scout knows",
  noContext: "No summarized context yet.",
  importContext: "Import context",
  retireFact: "Stop using",
  changeLog: "Change history",
  profileTitle: "Profile",
  profileLead: "How RoomScout addresses you in this private workspace.",
  displayName: "Display name",
  save: "Save",
  immutableLogin: "Username and sign-in remain unchanged: {username}",
  notificationsTitle: "Notifications",
  openInbox: "Open inbox",
  billingTitle: "Plan & usage",
  privacyTitle: "Privacy",
  privacyLead: "RoomScout stores searches, reviewed memories, approvals, and event metadata in Convex.",
  notStored: "Raw audio, passwords, 2FA values, cookies, and short-lived Live View links are not stored.",
  loading: "Loading settings …",
  unavailable: "This setting is not connected to a reliable service yet.",
  sourceDisclosure: "Sources apply only to the selected search. Excluded sources are not used.",
  notificationUnavailable: "Notifications currently appear only in RoomScout. Email, push, and browser settings are not available yet.",
  billingUnavailable: "RoomScout currently has no plan, billing data, or reliable user-level usage totals.",
  privacyUnavailable: "Data export and account deletion are not yet available as secure self-service actions.",
} as const satisfies DeepWiden<typeof liveSettingsCopy>;
