import type { DeepWiden } from "../types";
import type { liveScoutDe } from "../de/liveScout";

export const liveScoutEn = {
  preparing: "Your Scout is getting ready …",
  briefReviewAction: "Review search",
  activeStatus: "Scout at work",
  pausedLabel: "Paused",
  chatTitle: "Write to your Scout",
  voice: {
    cancel: "Cancel connection",
    connect: "Start conversation",
    connecting: "Connecting conversation …",
    controls: "Conversation controls",
    end: "End conversation",
    error: "Connection interrupted",
    interrupt: "Interrupt Scout",
    listening: "Listening",
    microphoneOff: "Turn microphone off",
    microphoneOn: "Turn microphone on",
    reconnect: "Restart conversation",
    scout: "Your Scout",
    speaking: "Your Scout is speaking",
    status: "Ready when you are",
    switchToText: "Switch to text",
    thinking: "Thinking for a moment",
    user: "You",
    title: "Tell me what you’re looking for.",
    region: "Conversation with your RoomScout",
    transcript: "Latest conversation turns",
    muted: "Microphone off",
    updating: "Updating your search …",
    queued: "Your message is queued …",
    outcomeUnknown: "The last step is still being checked.",
    ongoingCall: "Conversation in progress",
    returnToScout: "Return to Scout",
  },
  editBudget: "Edit budget",
  editSchedule: "Edit schedule",
  saveChanges: "Save changes",
  cancelChanges: "Discard changes",
  budgetLabel: "Maximum monthly budget",
  scheduleLabel: "Rehearsal times",
  requestPending: "Saving …",
  factUpdated: "Saved: {value}",
  editCriterion: "Edit {category}",
  factCategories: {
    ort: "location",
    budget: "budget",
    band: "band",
    zeit: "schedule",
    equip: "requirements",
  },
  thinking: "Your Scout is thinking …",
  scrollToEnd: "Jump to the newest messages",
  thinkingVerbs: {
    sorting: "Sorting through it …",
    brief: "Reviewing your search …",
    weighing: "Weighing the options …",
    writing: "Putting it into words …",
    listening: "Listening closely …",
    checking: "Checking the details …",
  },
  replying: "Your Scout is replying …",
  failed: "Reply failed.",
  retry: "Send again",
  tools: {
    rememberFact: "Remembering a detail",
    updateSearchDraft: "Updating your search",
    markSearchBriefReady: "Preparing the summary",
    answerDecision: "Applying your decision",
    replyToProvider: "Writing to the provider",
    createOutreachDraft: "Preparing an inquiry",
    createWebformDraft: "Preparing an inquiry",
    continueAutopilot: "Handling the request",
    default: "Working …",
  },
  candidatesTitle: "Candidates",
  candidatesEmpty: "No candidates yet. I’ll let you know as soon as I contact a room.",
  candidateState: {
    question: "Question for you",
    offer: "Offer ready",
    reply: "Reply received",
    asked: "contacted",
  },
  asideTitle: "Your room search",
  asideEdit: "Edit",
  radius: "{count} km radius",
  budgetValue: "Up to €{count} / month",
  bandProfile: "{count}-piece {text} band",
  factUnsure: "{text} · needs clarification",
  facets: {
    bandSize: "{count} people",
    equipmentStorage: "Drum kit provided or your own can stay",
    equipmentDrums: "Drum kit provided",
    equipmentPa: "PA provided",
    equipmentBackline: "Backline provided",
    accessParking: "Parking available",
    accessTransport: "Accessible by {text}",
    accessAnytime: "24-hour access",
    noiseNight: "Evening and night rehearsals allowed",
    roomSize: "{count} m²",
    contractMinTerm: "Minimum term {count} months",
    costDeposit: "€{count} deposit",
  },
  decisionWrite: "Or write instead",
  decisionReviewOffer: "Review offer",
  decisionOpenChat: "View in chat",
  openCandidates: "Candidates",
  openBrief: "Search",
  error: "That step did not work. Your search is still saved. Please try again.",
  intro: "Tell me about your band and the room you’re after. I’ll keep track of what matters.",
  introKnown: "I’ve saved your music context. What kind of rehearsal room are you looking for now?",
  ready: "Your search is ready. Review it and send me out when everything looks right.",
  working: "I’m on it.",
  workingDetail: "I’m looking for suitable rooms and checking open questions with providers. I’ll let you know when I need you.",
  sending: "I’m sending your inquiry.",
  waiting: "I’ve made the inquiry and I’m waiting for a reply.",
  reply: "The provider replied.",
  replyDetail: "I’m checking the reply and what is still open.",
  offer: "A room that fits your search.",
  offerDetail: "The open questions are resolved. Take a look at the offer.",
  paused: "Your search is paused.",
  pausedDetail: "Your search is still saved. Continue whenever you’re ready.",
  complete: "Your acceptance was delivered.",
  completeDetail: "I sent your approved acceptance. Your search is paused.",
  blocked: "I need your help here.",
  blockedDetail: "This step could not be completed yet. Open settings or write to me so we can continue.",
  decisionEyebrow: "Decision",
  decisionYes: "Yes, send it",
  decisionNo: "No, change it",
  decisionReview: "Review offer",
  decisionNotThis: "Not this one",
  decisionOpenRun: "Continue in browser",
  decisionReconnect: "Reconnect account",
  decisionAnswered: "Thanks, I’ll continue.",
  decisionOwnLabel: "Your answer",
  decisionChangeLabel: "What should change?",
  decisionInstructionHint: "Your Scout reads this. The provider will not see it.",
  decisionSubmit: "Answer",
  decisionRequired: "Choose an answer or write your own.",
  decisionScopes: "Affected details",
  decisionMessage: "This is what I would write:",
  changed: "Your search changed. I’m reviewing the offer again.",
  offerLabel: "Offer received",
  interimLabel: "Progress update",
  clarifying: "Still checking:",
  offerFallback: "Your rehearsal room",
  priceUnknown: "Price still to be confirmed",
  perMonth: "/ month",
  allIn: "including all confirmed recurring costs",
  extrasUnknown: "Additional costs still need to be confirmed",
  terms: "All terms",
  noPhoto: "No provider photo available",
  review: "Review offer",
  offerNote: "Before accepting, you review the terms and the message to the provider.",
  pendingAcceptance: "Sending acceptance …",
  unknownAcceptance: "Confirming delivery …",
  unconfirmedAcceptance: "Delivery is not confirmed. Check the conversation.",
  failedAcceptance: "The acceptance could not be sent. Check the conversation.",
  sentAcceptance: "Acceptance sent · {time}",
  viewMessages: "View messages",
  openQuestions: "Still open",
  editBrief: "Change something",
  activate: "Start the Scout",
  activating: "Scout is starting …",
  activateNote: "I search and make non-binding inquiries independently. Only you can make a binding commitment.",
  location: "Location",
  band: "Band",
  arrangement: "Room",
  budget: "Budget",
  schedule: "Schedule",
  requirements: "What matters to you",
  sharing: "Share room",
  music: "Music",
  instruments: "Instruments",
  connections: "Meet bands",
  permanent: "Private room",
  shared: "Shared room",
  hourly: "By the hour",
  sharingYes: "Open to sharing",
  sharingNo: "Only for your band",
  connectionsYes: "Open to meeting other bands",
  connectionsNo: "Room search only",
} as const satisfies DeepWiden<typeof liveScoutDe>;
