import type { DeepWiden } from "../types";
import type { liveOperatorCopy } from "../../operator/live/copy";

export const liveOperatorEn = {
  accessChecking: "Checking operator access …",
  accessDenied: "Operator access required",
  title: "Operator view",
  operations: "Operations",
  environment: "Internal operations",
  avatarInitials: "OP",
  avatarLabel: "Operator",
  footer: "Internal operations view · Live data",
  overview: "Overview",
  sources: "Sources",
  tasks: "Tasks",
  integrations: "Integrations",
  flags: "Feature flags",
  diag: "Diagnostics",
  overviewTitle: "Operations at a glance",
  overviewSubtitle: "Providers, sources, and waiting tasks.",
  sourcesTitle: "Sources",
  sourcesSubtitle: "Technical access to monitored sources.",
  tasksTitle: "Tasks",
  tasksSubtitle: "Current operational events and processes.",
  integrationsTitle: "Integrations",
  integrationsSubtitle: "External service configuration.",
  flagsTitle: "Feature flags",
  flagsSubtitle: "Controls for managed product features.",
  diagTitle: "Diagnostics",
  diagSubtitle: "Trace events and configuration errors.",
  subtitle: "Live state of the active RoomScout services.",
  tools: "Tools",
  advancedTools: "Advanced tools",
  refresh: "Check configuration again",
  refreshing: "Checking configuration …",
  bounded: "Bounded live sample",
  liveMetrics: "Live metrics",
  attention: "Areas needing attention: {count}",
  noAttention: "No issues in the current sample.",
  viewTasks: "View tasks",
  viewFlags: "View flags",
  activitySummary: "Events in the current sample: {count}",
  noActivity: "No operational events yet.",
  noDiagnostics: "No diagnostic events in the current sample.",
  recentEvents: "Recent events",
  allTasks: "All",
  attentionOnly: "Needs attention",
  noAttentionTasks: "No concerning tasks in the current sample.",
  providerCheckOnly: "Configuration check only, no live test",
  engineLabel: "Engine",
  engineDefault: "Default",
  engineInactive: "inactive",
  configured: "Configured",
  notChecked: "Not checked yet",
  incomplete: "Incomplete",
  disabled: "Disabled",
  clientOnly: "Only verifiable in the client",
  checkFailed: "The configuration check failed. Please try again.",
  checkComplete: "Configuration check complete.",
  configuration: "Configuration:",
  health: "Operational health:",
  healthUnknown: "Not checked live",
  configuredNotHealthy: "Configured does not necessarily mean reachable or healthy. This check only reads the current configuration.",
  sourcesLoading: "Loading sources …",
  noSources: "No sources in the current live result.",
  unknown: "Not provided",
  neverChecked: "Not checked yet",
  checkNow: "Check sources now",
  checkRunning: "Check running …",
  checkStartFailed: "The source check could not be started. Please try again.",
  demoScopeNote: "The demo run is limited to roomscout.dev. Personal source preferences do not change this status.",
  advancedView: "Advanced view",
  sourceToggleLabel: "Enable {name}",
  sourceToggleFailed: "The source could not be changed. Please try again.",
  sourceReviewRequired: "This source has not been approved and cannot be enabled.",
  connection: {
    demo: "Connected · Demo access",
    connected: "Connected",
    inactive: "Inactive",
    degraded: "Degraded",
  },
  sourceColumns: {
    source: "Source",
    region: "Region",
    connection: "Connection",
    lastCheck: "Last demo check",
    toggle: "Active",
  },
  flagsUnavailable: "Feature flags are not connected to live settings yet.",
  flagsLimitation: "This view therefore does not infer flag states and cannot save changes.",
  saveFlags: "Save changes",
  unknownState: "Unknown",
  flagRows: {
    voice: { label: "Voice Scout", effect: "Controls access to the voice Scout." },
    publicSearch: { label: "Public source search", effect: "Controls search across approved public sources." },
  },
  taskColumns: { process: "Process", source: "Source", status: "Status", next: "Next step" },
  unavailableDash: "—",
  details: "Details",
  diagLimitation: "Diagnostics show the bounded event sample and configuration errors; they do not run an independent service test.",
  openSignals: "Open signal queue",
  openOutreach: "Open approvals and delivery",
  openAudit: "Open audit log",
  open: "Open",
  toolLabels: {
    sources: "Sources and monitoring",
    signals: "Signal queue",
    outreach: "Approvals and delivery",
    inbox: "Scout mailbox",
    audit: "Audit log",
  },
  metrics: {
    publishedSignals: "Published signals",
    staleSignals: "Stale signals",
    detailBacklog: "Detail backlog",
    detailFailures: "Failed details",
    awaitingApproval: "Awaiting approval",
    repliedThreads: "Replies",
    unhealthySources: "Unhealthy sources",
    activeVoiceSessions: "Active voice sessions",
    activeMailboxes: "Active Scout mailboxes",
  },
  providers: {
    convexAiGateway: "Convex AI Gateway",
    firecrawl: "Firecrawl",
    agentmail: "AgentMail",
    browserbase: "Browserbase",
    mapbox: "Mapbox",
    openaiDirect: "OpenAI direct",
  },
  providerRoles: {
    convexAiGateway: "Text & evaluation",
    firecrawl: "Source monitoring · Portal access",
    agentmail: "Scout mailboxes",
    browserbase: "Portal access",
    mapbox: "Maps and geocoding",
    openaiDirect: "Voice & embeddings",
  },
} as const satisfies DeepWiden<typeof liveOperatorCopy>;
