import type { DeepWiden } from "../types";
import type { scoutDe } from "../de/scout";

export const scoutEn = {
  chrome: {
    wordmark: "roomscout",
    badge: { running: "Scout at work", paused: "Search paused" },
    pause: { pause: "Pause search", resume: "Resume search" },
    avatar: { aria: "Profile menu" },
    menu: { subtitle: "Personal workspace", settings: "Settings", backToScout: "Back to Scout" },
    settingsFooter: "Design prototype · Sample data",
  },
  toast: {
    action: "Go to Scout",
    dismiss: { aria: "Close" },
    approval: "Your Scout is waiting for approval",
    clarification: "Your Scout has a question",
    decision: "Your Scout needs a decision",
    candidates: "Your Scout has rooms to compare",
    offer: "An offer has arrived",
  },
  hint: {
    voiceDisabled: "Voice Scout is disabled in this demo. The conversation continues in text mode.",
    scoutNotDone: "Your Scout is not finished yet. You can reply in a moment.",
    freeTextDiscovery: "Prototype: free text is not interpreted here. Use the prepared answer or phrase it similarly.",
    sideNote: "Prototype: additional notes are not interpreted here. Your Scout continues with the current search.",
    micSimulatedAutopilot: "Prototype: the microphone is simulated. The demo continues without voice input.",
    clarificationNotUnderstood: "Prototype: this answer is not interpreted. Reply with “Yes, Wednesday works” or “No, Thursday is important.”",
    micSimulatedClarification: "Prototype: the microphone is simulated. Reply by clicking or typing.",
    freeQuestion: "Prototype: free questions are not interpreted here. Use the prepared question.",
  },
  transcript: {
    title: "Transcript",
    close: { aria: "Close transcript" },
    empty: "No conversation turns yet.",
    who: { scout: "Your Scout", user: "You" },
  },
  welcome: {
    greeting: "Hey {name}.",
    headline: "Let’s find your rehearsal room.",
    cta: { voice: "Talk to Scout", text: "Write instead" },
    footnote: "You tell me what matters. Your Scout handles the search.",
  },
  discovery: {
    speaker: { scout: "Your Scout", user: "You" },
    state: { listening: "Listening", micOff: "Microphone off", thinking: "Thinking for a moment" },
    ended: {
      text: "Conversation ended. Your needs remain saved as a draft.",
      resume: "Resume conversation",
      viewBrief: "View search",
    },
    controls: {
      micOn: "Microphone on",
      micOff: "Microphone off",
      transcript: "Transcript",
      end: "End conversation",
      switchToText: "Switch to text",
    },
    input: {
      aria: "Message your Scout",
      placeholder: { awaiting: "Reply to your Scout …", busy: "Your Scout is speaking …" },
    },
    send: { aria: "Send" },
    switchToVoice: { aria: "Switch to voice" },
    links: { transcript: "Transcript", end: "End conversation" },
    inlineBrief: { label: "Your room search" },
  },
  script: {
    s1: { scout: "Hey Herzbuben! Tell me briefly: where are you looking, and what matters to you?" },
    s2: { user: "We’re a four-piece band looking for a shared room in Stuttgart. Up to €400 a month." },
    s3: { scout: "Which days work for rehearsals?" },
    s4: { user: "Thursdays from 19:00 would be good." },
    s5: { scout: "Does anything need to be provided or stay in the room?" },
    s6: { user: "Our drum kit needs to stay there. We bring our own amplifiers." },
    s7: { user: "And we’d rather keep the budget under €350." },
    s8: { scout: "Got it, up to €350. Here’s how I’d search for you. Should I get started?" },
    memory: { amps: "The band brings its own amplifiers" },
    resumeSuggestion: "Yes, get started.",
  },
  facts: {
    ort: { text: "Stuttgart", umland: "Stuttgart and nearby" },
    budget: {
      "400": "Up to €400 / month",
      "350": "Up to €350 / month",
      lower: { "400": "up to €400 / month", "350": "up to €350 / month" },
      compact: { "400": "up to €400", "350": "up to €350" },
    },
    band: "Shared room · 4 people",
    zeit: { donnerstag: "Thursdays from 19:00", mittwochOderDonnerstag: "Wednesday or Thursday from 19:00" },
    equip: "Drum kit can stay in the room",
  },
  brief: {
    headline: "Here’s how I’ll search for you.",
    title: "Your room search",
    edit: { aria: "Edit search" },
    editRow: { aria: "Edit criterion" },
    cta: "Start the Scout",
    caption: {
      line1: "I search and make non-binding inquiries independently.",
      line2: "Only you can make a binding commitment.",
    },
    changeMore: "Change something",
    backToConvo: "Back to conversation",
    save: "Apply",
    cancel: "Cancel",
    sheet: { count: { one: "1 search fact", other: "{count} search facts" } },
  },
  autopilot: {
    headline: "I’m on it.",
    resume: "Continue",
    status: {
      start: "Got it. I’ll find suitable rooms and check the details. I’ll let you know when I need you.",
      searching: "I’m looking for suitable rooms in Stuttgart.",
      found: "A room in Stuttgart-West could fit. I’m checking the details.",
      asked: "I asked whether your drum kit can stay and whether Thursday is available.",
      waiting: "Now I’m waiting for a reply.",
      followUp: "I’ll confirm that Wednesday works for you and ask for the offer.",
      alternative: "I’ll ask for an alternative to Wednesday and keep searching.",
      noSource: "No usable source is currently selected for inquiries. Choose a source in Settings.",
      noAccess: "My access to roomscout.dev needs a new sign-in before I can make an inquiry.",
      prepared: "I prepared an inquiry. It will be sent only after you approve it.",
      searchAgain: "I’m searching again with the new criteria.",
      requestOffer: "I’m asking {roomName} for an offer and checking the details.",
      keepSearching: "Got it. I’ll keep searching and let you know when something new comes up.",
      keepWaiting: "Got it. I’ll keep searching in the background and let you know.",
    },
    approval: {
      eyebrow: "Approval needed",
      toLabel: "To: ",
      to: "Provider · Room in Stuttgart-West · roomscout.dev",
      message: "Hello, we’re {name}, a four-piece band from Stuttgart. We’re looking for a shared rehearsal room, {budget}, on Thursdays from 19:00. We need to leave our drum kit in the room. Is the room in Stuttgart-West still available? Best, {name} (via RoomScout)",
      budget: { fallback: "up to €350 / month" },
      contactOff: "Contacting providers is disabled in your autonomy settings. This message will be sent only with your explicit approval.",
      release: "Approve message",
      changeAutonomy: "Change autonomy",
    },
    blocked: {
      chooseSource: "Select source",
      accessText: "Your portal access to roomscout.dev needs a new sign-in.",
      accessLink: "Go to access settings",
    },
    brief: {
      title: "Your room search",
      pill: { compact: "Stuttgart · {budget}", budget: { fallback: "up to €350" } },
    },
    activity: { show: "View activity", hide: "Hide activity" },
    sideNote: {
      placeholder: "Anything else you’d like to tell me?",
      aria: "Message your Scout",
      voice: { aria: "Talk to Scout" },
    },
    footnote: "You can close the app. I’ll let you know when I need you.",
  },
  activity: {
    start: "Search started",
    found: { text: "Room found in Stuttgart-West", meta: "roomscout.dev · Demo portal" },
    contacted: "Provider contacted through the portal",
    waiting: "Waiting for a reply",
    notif: "Portal notification received",
    read: "New portal message read",
    confirmed: "Wednesday confirmed, offer requested",
    alt: "Alternative to Wednesday requested",
    offer: "Offer received",
    declined: "Provider declined: Thursday unavailable",
    noMatch: "No other suitable room found in Stuttgart",
    found2: { text: "Three rooms prepared for comparison", meta: "roomscout.dev · Demo portal" },
    briefAdjusted: "Search adjusted: {label}",
    offerRequested: "Offer requested: {short}",
  },
  clarification: {
    headline: "One quick question.",
    eyebrow: "Room in Stuttgart-West",
    question: "Thursday is taken. Would Wednesday from 19:00 work too?",
    detail: "€280 including utilities. Your drum kit can stay in the room.",
    yes: {
      text: "Yes, Wednesday works",
      userText: "Yes, Wednesday works too.",
      reply: "Great, Wednesday works too. I’ll check the rest.",
    },
    no: {
      text: "No, Thursday is important",
      userText: "No, Thursday is important.",
      reply: "Understood. Thursday stays. I’ll ask about an alternative and keep searching.",
    },
    input: { placeholder: "Message your Scout …", aria: "Reply to your Scout" },
    send: { aria: "Send" },
    voice: "Speak",
  },
  offer: {
    headline: "A room that fits your search.",
    stale: { text: "The offer needs to be reviewed again after your change.", link: "View details" },
    photo: { alt: "Rehearsal room with a drum kit and acoustic panels", pending: "Provider photo pending" },
    eyebrow: "Offer received",
    title: "Your {roomName}",
    price: { perMonth: "/ month", note: "including utilities" },
    cta: "Review offer",
    footnote: "We’ll review all terms before any acceptance.",
    prompt: { text: "Would you like me to explain the offer?", speaking: "Your Scout" },
    talk: "The offer is €280 including utilities. You can rehearse on Wednesdays from 19:00 to 22:00, and your drum kit can stay. Would you like me to explain the remaining terms?",
    talkCta: "Talk to Scout",
    brief: { title: "Your room search" },
    briefPill: "Search",
  },
  review: {
    headline: "Does this work for you?",
    price: { note: "including utilities" },
    terms: {
      shared: "Shared room · 4 people",
      storage: "Drum storage confirmed",
      start: "Start: October 1, 2026",
      deposit: "No deposit",
      notice: "Notice period: one month to the end of the month",
      show: "Show full terms",
      hide: "Hide full terms",
      full: "Shared use of the room in Stuttgart-West by four band members, Wednesdays 19:00–22:00. Monthly rent €280 including utilities, starting October 1, 2026. No deposit. One month’s notice to the end of the month. Your drum kit may remain in the room. The band provides its own amplifiers.",
      demoNote: "Demo terms. The complete provider offer would be available here in the full product.",
    },
    accept: {
      text: "Accept offer",
      disclaimer: "Your confirmation would authorize the Scout to make a binding acceptance with the provider. Nothing is sent in this demo.",
    },
    question: {
      toggle: "Clarify another question",
      prepared: "What happens after acceptance?",
      answer: "I make the binding acceptance with the provider and send you confirmation with all terms. You can start rehearsing on October 1. Nothing is sent in this demo.",
      placeholder: "Ask your Scout …",
      aria: "Question for your Scout",
      send: { aria: "Send" },
    },
  },
  complete: {
    headline: "Your next rehearsal room is ready.",
    subline: "Demo complete—no real acceptance was sent.",
    summary: "{short} · {price} · {timeLower}",
    restart: "View demo again",
  },
  deadEnd: {
    headline: "I’m stuck here for now.",
    eyebrow: "Room in Stuttgart-West",
    body: "The provider cannot offer Thursday. I have not found another room in Stuttgart that fits your search right now.",
    prompt: "What could work for you? I’ll change your search only if you ask me to.",
    option: {
      budget: { title: "Budget up to €{budget}", sub: "Adds more rooms in Stuttgart to the search." },
      umland: { title: "Include nearby towns", sub: "Esslingen, Ludwigsburg, Fellbach · 20 to 30 minutes away." },
      zeit: { title: "Allow Wednesday", sub: "The room in Stuttgart-West would be available. Thursday stays saved." },
    },
    keepWaiting: "Change nothing and keep searching",
    reply: {
      budget: "Got it, up to €400. I’ll search Stuttgart again.",
      umland: "Got it. I’ll include nearby towns: Esslingen, Ludwigsburg, and Fellbach.",
      zeit: "Got it, Wednesday works too. I’ll contact the room in Stuttgart-West again.",
    },
  },
  candidates: {
    headline: "Three rooms worth considering.",
    subline: "I’ve laid out the differences. You decide where I inquire.",
    badge: { best: "My pick" },
    photo: { pending: "Provider photo pending" },
    budget: { ok: "Within budget", over: "Over your budget (€{budget})" },
    cta: "Ask about this room",
    keepSearching: "None fit, keep searching",
    west: {
      name: "Room in Stuttgart-West",
      short: "Stuttgart-West",
      price: "€280 / month",
      time: "Wednesdays, 19:00–22:00",
      timeLower: "Wednesdays 19:00–22:00",
      storage: "Drum kit can stay in the room",
      way: "12 min by light rail",
      size: "approx. 28 m² · shared with one band",
      note: "The least expensive room, but only available on Wednesdays.",
    },
    esslingen: {
      name: "Room in Esslingen",
      short: "Esslingen",
      price: "€320 / month",
      time: "Thursdays, 19:00–23:00",
      timeLower: "Thursdays 19:00–23:00",
      storage: "Drum kit can stay in the room",
      way: "25 min by suburban train",
      size: "approx. 35 m² · shared with two bands",
      note: "Your preferred day, but outside Stuttgart.",
    },
    ost: {
      name: "Room in Stuttgart-Ost",
      short: "Stuttgart-Ost",
      price: "€350 / month",
      time: "Thursdays, from 20:00",
      timeLower: "Thursdays from 20:00",
      storage: "Drum kit would need to be packed away",
      way: "18 min by light rail",
      size: "approx. 22 m² · shared with three bands",
      note: "At your budget limit, and the drum kit cannot stay.",
    },
  },
  data: {
    name: { default: "Herzbuben" },
    initials: { default: "HB" },
    session: {
      held: "Conversation paused · continues when you return",
      paused: "Search paused",
      running: "Scout at work",
    },
    usage: { talk: "Not tracked yet" },
    export: { hinweis: "Local demo data from the design prototype" },
    knowledge: {
      origin: { conversation: "From the conversation · part of your search" },
      genre: { text: "Hard rock and alternative", origin: "Demo band profile" },
      mates: { text: "Similar musical taste matters in co-users", origin: "Your Scout’s assumption" },
      amps: { text: "You bring your own amplifiers", origin: "From the conversation" },
    },
    log: {
      factCorrected: "Detail corrected: {label}",
      briefAdjusted: "Search adjusted: {label}",
      rulesUpdated: "Autonomy updated",
      knowledgeImported: "Imported {count} details from sample context",
    },
    summary: {
      empty: "I don’t know anything about you yet. Tell me in our next conversation.",
      band: {
        fourFromOrt: "You are a four-piece band from {ort}.",
        four: "You are a four-piece band.",
        fromOrt: "You are a band from {ort}.",
        plain: "You are a band.",
      },
      seeks: {
        sharedAndStorage: "You are looking for a shared rehearsal room where you can leave your drum kit.",
        shared: "You are looking for a shared rehearsal room.",
        roomAndStorage: "You are looking for a rehearsal room where you can leave your drum kit.",
        room: "You are looking for a rehearsal room.",
        storage: "You want to leave your drum kit there.",
      },
    },
    source: {
      roomscout: { name: "roomscout.dev", desc: "Controlled demo portal" },
      musiker: { name: "Musicians in your city", desc: "Stuttgart · Public listings" },
      bandnet: { name: "Bandnet Hamburg", desc: "Hamburg · Different region" },
    },
    time: { today: "Today, {time}" },
  },
} as const satisfies DeepWiden<typeof scoutDe>;
