import type { DeepWiden } from "../types";
import type { settingsDe } from "../de/settings";

export const settingsEn = {
  nav: {
    back: "Back to Scout",
    aria: "Settings",
    groupScout: "Your Scout",
    groupAccount: "Your account",
    item: {
      sources: "Sources & access",
      autonomy: "Autonomy",
      knowledge: "What your Scout knows",
      profile: "Profile",
      notifications: "Notifications",
      billing: "Plan & usage",
      privacy: "Privacy",
    },
    footer: { role: "Personal workspace" },
  },
  session: {
    working: "Scout at work",
    paused: "Search paused",
    held: "Conversation paused · continues when you return",
  },
  host: { caption: "Design prototype · Sample data" },
  sources: {
    title: "Where may your Scout search?",
    subtitle: {
      withOrder: "Sources for your search in {city}.",
      noOrder: "Sources apply to a specific search.",
    },
    noOrder: {
      title: "Create a search first.",
      body: "Sources always apply to a specific search. Your portal connections remain separate.",
      cta: "Go to Scout",
    },
    auto: {
      title: "Select relevant sources automatically",
      sub: "Your exclusions are preserved.",
      saved: "Saved",
    },
    list: { label: "Your sources", scope: "For this search" },
    noUsable: {
      text: "No usable source is currently selected. Your Scout cannot continue searching.",
      cta: "Select source",
    },
    status: {
      excluded: "Not included",
      connected: "Connected",
      expired: "Sign in again",
      public: "No sign-in required",
      indexed: "Indexed source",
      reviewed: "Reviewed source",
      contactDisabledDemo: "Contact disabled in demo",
    },
    row: { saved: "Saved", switchAria: "Use {name} for this search", detailsAria: "Details" },
    detail: {
      portalProfile: "Portal profile: {profile}",
      portalScope: "Read listings and exchange messages",
      publicListings: "Public listings may be included. The contact method depends on the listing.",
      indexedReadOnly: "Indexed public listings can be read. Contact is disabled in the demo.",
      reviewedReadOnly: "Source coverage was reviewed, but no indexed listings are evidenced here yet. Contact is disabled in the demo.",
      demoInactive: "Inactive in this demo",
      outOfRegion: "Hamburg is outside your search area. No sign-in is needed for it.",
      offHint: "No new inquiries through this source. Existing conversations remain visible.",
      manageConnection: "Manage connection",
      openLogin: "Open sign-in",
    },
    address: {
      title: "Your Scout address",
      value: "herzbuben@scout.example",
      hint: "For portal sign-ins and replies to your Scout.",
      copy: "Copy",
      copied: "Copied",
      copyFail: "Copying did not work. Select the address and copy it manually.",
    },
    more: {
      show: "View more sources",
      hide: "Hide more sources",
      note: "Excluding a source does not delete its portal account.",
      searchPlaceholder: "Search source or region …",
      searchAria: "Search sources",
      state: { available: "Available", loginNeeded: "Sign-in required", unavailable: "Not available yet" },
      action: { exclude: "Exclude", include: "Include", unavailable: "Unavailable", contactDisabled: "Contact disabled in demo" },
      example: {
        name: "Southern Rehearsal Room Exchange (sample)",
        region: "Baden-Württemberg",
        title: "This sample source is not connected in the prototype.",
      },
      empty: "No source found. This list shows only the available demo sources.",
      footnote: "Demo sources. This is not a complete list of portals.",
    },
    demo: {
      roomscout: { name: "roomscout.dev", desc: "Controlled demo portal", profile: "Herzbuben" },
      musiker: { name: "Musicians in your city", desc: "Stuttgart · Public listings" },
      bandnet: { name: "Bandnet Hamburg", desc: "Hamburg · Different region" },
    },
  },
  connection: {
    title: "Connection to roomscout.dev",
    closeAria: "Close",
    field: { profile: "Portal profile", state: "Status", lastAccess: "Last successful access" },
    state: { connected: "Connected", expired: "Sign in again", disconnected: "Not connected" },
    lastAccess: { connectedNone: "No access yet in this demo", none: "No access yet" },
    explain: "This connection lets your Scout read listings on roomscout.dev, message providers, and retrieve portal replies. The prototype does not store credentials.",
    disconnect: "Disconnect",
    confirm: {
      body: "RoomScout will lose the saved access. Your account on the portal will remain.",
      stay: "Stay connected",
      disconnect: "Disconnect",
    },
    disconnected: {
      hint: "Connect before reading or sending private messages.",
      cta: "Open sign-in",
    },
    login: {
      eyebrow: "Demo sign-in simulation",
      body: "This is not a real roomscout.dev sign-in page. No credentials are requested or stored. Sign-in is simulated locally.",
      cancel: "Cancel",
      finish: "Complete demo sign-in",
    },
    msg: {
      removed: "Access removed. Your portal account remains.",
      saved: "Access saved. Your Scout can continue.",
    },
  },
  autonomy: {
    title: "How your Scout works",
    subtitle: "You decide how independently I proceed.",
    modeGroupAria: "Operating mode",
    mode: {
      autopilot: { title: "Autopilot", sub: "Search, inquire, and clarify details." },
      review: { title: "Review every action", sub: "Review messages before they are sent." },
    },
    actions: {
      label: "What I may handle independently",
      details: "Contact includes initial inquiries and follow-ups about availability, price, and equipment. Viewings are suggested, never booked. A search listing would be public and contain only approved information.",
    },
    details: { toggle: "Details" },
    action: {
      contact: "Contact providers and follow up",
      viewings: "Suggest viewing times",
      publishAd: "Publish a room-wanted listing",
    },
    share: {
      label: "What I may share",
      details: "Band profile: band name, lineup, genre, preferred rehearsal times, and Scout address. Private: personal phone numbers and exact home addresses. This permission applies independently of the operating mode.",
      profile: "Band profile, availability, and Scout address",
      private: "Private phone number and exact address",
    },
    lock: {
      title: "Binding decisions stay with you.",
      sub: "Contracts, bookings, and payments always require your approval.",
    },
    saved: "Autonomy updated",
    cancel: "Cancel",
    save: "Save changes",
  },
  discard: {
    title: "Discard changes?",
    body: "Your autonomy settings have unsaved changes.",
    keep: "Keep editing",
    discard: "Discard",
  },
  knowledge: {
    title: "What I know about you",
    subtitle: "Correct me at any time. You decide what I remember.",
    summary: {
      demo: "You are a four-piece band from Stuttgart. You are looking for a shared rehearsal room where you can leave your drum kit.",
      editAria: "Edit underlying details",
    },
    tab: { band: "Your band", alltag: "Routine & travel", ausstattung: "Equipment" },
    empty: {
      band: "I don’t know anything about your band yet. Tell me in our next conversation.",
      alltag: "I don’t know about your travel needs yet. Tell me in our next conversation.",
      ausstattung: "I don’t know about your equipment yet. Tell me in our next conversation.",
    },
    edit: {
      inputAria: "Edit detail",
      save: "Save",
      cancel: "Cancel",
      factHint: "This detail is part of your search and will be updated there too.",
    },
    badge: { assumed: "Needs confirmation" },
    origin: {
      line: "Source: {origin}. Used for: {usage}.",
      confirmedByYou: "Confirmed by you · preference, not an exclusion",
      imported: "Imported from sample context",
    },
    usage: {
      fact: "Search and inquiries",
      preference: "Assessing rooms and co-users, not a hard filter",
    },
    action: { confirm: "Correct", dismiss: "Not important", editAria: "Edit", menuAria: "More" },
    menu: { retire: "Stop using", origin: "View source" },
    undo: { text: "“{text}” will no longer be used.", action: "Undo" },
    log: {
      show: "View change history",
      hide: "Hide change history",
      empty: "No changes in this demo yet.",
      demoEntry: "Budget corrected: 400 → €350",
      demoWhen: "Today",
      entry: {
        corrected: "Detail corrected: {text}",
        retired: "Stopped using detail: {text}",
        confirmed: "Preference confirmed: {text}",
        dismissed: "Assumption dismissed: {text}",
        undo: "Undone: {text}",
        imported: "Imported {n} details from sample context",
        rulesUpdated: "Autonomy updated",
      },
    },
    import: {
      title: "Bring your existing context",
      sub: "Import music context from ChatGPT or Claude.",
      cta: "Import context",
      done: { one: "Imported {n} detail.", other: "Imported {n} details." },
    },
    managePrivacy: "Manage saved information",
    toast: {
      factRetire: "This detail belongs to your search. Edit it there or correct it here.",
      dismissed: "Removed from active preferences. Other music details remain.",
      noItems: "No details yet.",
    },
    demo: {
      f_band: { text: "Shared room · 4 people" },
      f_budget: { text: "Up to €350 / month" },
      f_ort: { text: "Stuttgart" },
      f_zeit: { text: "Thursdays from 19:00" },
      f_equip: { text: "Drum kit can stay in the room" },
      k_genre: { text: "Hard rock and alternative" },
      k_mates: { text: "Similar musical taste matters in co-users" },
      k_amps: { text: "You bring your own amplifiers" },
      origin: {
        fact: "From the conversation · part of your search",
        bandprofile: "Demo band profile",
        assumption: "Your Scout’s assumption",
        conversation: "From the conversation",
      },
    },
  },
  import: {
    step: "Step {n} of 3",
    closeAria: "Close",
    title: { "1": "Prepare context", "2": "Paste result", "3": "Review before importing" },
    step1: {
      intro: "Copy this prompt into ChatGPT or Claude and ask it to summarize your music-related context.",
      prompt: "Summarize only the music-related context you actually know about me and my band: lineup, instruments, genre, rehearsal-room needs, budget, availability, and relevant travel needs. Do not invent anything, clearly mark uncertainty, and omit passwords, contact details, and unrelated personal information. If you have no such context, say so explicitly.",
      copy: "Copy prompt",
      copied: "Copied",
      next: "Continue",
    },
    step2: {
      label: "Paste music context",
      placeholder: "Paste summary here …",
      hint: "Do not paste credentials or sensitive information. The text is not stored after import.",
      useExample: "Use example",
      back: "Back",
      check: "Review details",
    },
    example: "We are a five-piece band from Stuttgart with two guitars, bass, drums, and vocals, playing hard rock and alternative. We usually rehearse after 19:00 and travel by car, so parking would help. I’m unsure about the budget, probably up to €300 a month.",
    step3: {
      free: "This prototype does not evaluate free text automatically. Use the prepared example for the demo; add your own details in conversation or directly in the knowledge list.",
      useExample: "Use example",
      intro: "Simulated analysis of the example. Choose what your Scout should remember.",
    },
    cand: {
      i1: "Five band members",
      i2: "Lineup: two guitars, bass, drums, vocals",
      i3: "Usually rehearses after 19:00",
      i4: "Travels by car, parking helpful",
      i5: "Budget up to €300 (uncertain)",
    },
    conflict: {
      band: "Conflicts with “{text}” in the current search. The search will not be overwritten.",
      budget: "Marked uncertain and differs from the search ({text}).",
      budgetPlain: "Marked uncertain.",
    },
    pickCount: "{n} selected",
    back: "Back",
    apply: "Import selected details",
  },
  profile: {
    title: "Your profile",
    subtitle: "How should your Scout address you?",
    nameLabel: "Display name",
    save: "Save",
    saved: "Name saved. Address and initials have been updated.",
    login: {
      title: "Demo sign-in",
      sub: "Local sample identity “herzbuben” · no real sign-in",
      badge: "Design prototype",
    },
    footnote: "External portal accounts and your Scout address are not renamed when your display name changes.",
    initialsFallback: "–",
  },
  notif: {
    title: "When should I notify you?",
    subtitle: "Important updates always reach you in the app.",
    decision: {
      label: "When your decision is needed",
      sub: "Questions, approvals, and offers for you to review",
    },
    offer: { label: "When an offer arrives", sub: "Concrete offers with terms" },
    digest: { label: "General progress summary", sub: "An occasional overview of searches and inquiries" },
    channel: { label: "Channel", aria: "Channel", app: "In the app", mail: "Scout address (simulated)" },
    footnote: "Preferences are stored locally. No browser permission is requested and no real email is sent. Required decisions stay visible in the app even when notifications are off.",
    toast: { saved: "Saved" },
  },
  billing: {
    title: "Plan & usage",
    subtitle: "Your access, activity, and billing.",
    access: {
      label: "Your access",
      plan: "Demo access",
      sub: "No paid subscription is active.",
      cta: "View plans",
    },
    tariff: {
      title: "Plans have not been set yet.",
      body: "You can try RoomScout in this prototype. Nothing will be charged.",
    },
    usage: {
      label: "Activity in September",
      searches: { one: "Active search", other: "Active searches" },
      contacted: "Providers contacted",
      talk: "Conversations with Scout",
      talkNone: "Not tracked yet",
      footnote: "Activity overview, not billing units.",
    },
    payment: { title: "Payment details", sub: "No payment method saved", cta: "Manage" },
    address: { title: "Billing address", sub: "Not provided yet", cta: "Add" },
    pay: {
      title: "Payment management is not set up yet.",
      body: "This is where you would manage payment and billing details later.",
    },
    invoices: { label: "Invoices", emptyTitle: "No invoices yet", emptySub: "Your receipts will appear here later." },
    footnote: "Product concept · No payment integration yet",
  },
  privacy: {
    title: "Your data, your control",
    subtitle: "What RoomScout stores locally in this demo.",
    stored: {
      title: "Saved details",
      sub: "{n} details about your band and search",
      cta: "View saved details",
    },
    transcript: {
      title: "Conversation history",
      sub: "Transcripts of your Scout conversations, available in the app",
    },
    portals: {
      title: "Portal connections",
      sub: { one: "{n} connected portal account, simulated", other: "{n} connected portal accounts, simulated" },
      cta: "Manage portal connections",
    },
    export: {
      title: "Export",
      sub: "Exports only this prototype’s local demo data as JSON.",
      cta: "Export demo data",
      filename: "roomscout-demo-data.json",
      note: "Local demo data from the design prototype",
    },
    delete: {
      title: "Delete account",
      body: "The final product would permanently delete all account data here. This demo does not support that yet; restarting the demo does not replace deletion.",
    },
    vendors: {
      title: "Service providers",
      body: "RoomScout uses Convex, Firecrawl, AgentMail, Browserbase, and OpenAI for text and evaluation, source monitoring, Scout mailboxes, portal access, and voice. The data processed depends on the feature and would be explained separately in the product.",
    },
    toast: { exported: "Local demo data exported.", exportFailed: "Export failed." },
  },
} as const satisfies DeepWiden<typeof settingsDe>;
