export const appRoutesDe = {
  restoring: "Deine Sitzung wird geladen …",
  checkingOperator: "Der Betreiberzugang wird geprüft …",
  operatorTitle: "Nur für Betreiber.",
  operatorDetail: "Mit deinem Konto kannst du den Scout nutzen. Die Betreiberansicht ist für freigeschaltete Konten vorgesehen.",
  scout: "Zum Scout",
  errorTitle: "Diese Ansicht konnte nicht geladen werden.",
  errorDetail: "Versuche es erneut. Deine gespeicherten Daten bleiben erhalten.",
  reload: "Erneut laden",
  home: "Zur Startseite",
  profileMenu: "Profilmenü",
  settings: "Einstellungen",
  messages: "Nachrichten",
  operator: "Betreiberansicht",
  signOut: "Abmelden",
  signOutError: "Abmelden hat gerade nicht geklappt. Bitte versuche es erneut.",
  workspace: {
    home: "RoomScout-Startseite",
    account: "Dein Konto",
    accountNavigation: "RoomScout und Konto",
    personalScout: "Dein persönlicher Scout",
    scout: "Scout",
    explore: "Anzeigen entdecken",
    search: "Euer Suchauftrag",
    map: "Karte",
  },
  auth: {
    personalScout: "Dein persönlicher RoomScout",
    signUpTitle: "Euer nächster Raum beginnt hier.",
    signUpSubtitle: "Ein Gespräch. Ein Suchauftrag. Dein Scout bleibt dran.",
    signInTitle: "Schön, dass du wieder da bist.",
    signInSubtitle: "Deine Suche und eure Gespräche warten auf dich.",
  },
  onboarding: {
    eyebrow: "Dein Musikerprofil",
    title: "Wen vertritt dein Scout?",
    lead: "Diese kurze Vorstellung verwendet RoomScout bei Anfragen an Anbieter. Musik und Raumwünsche besprecht ihr danach mit dem Scout.",
    firstName: "Vorname",
    firstNamePlaceholder: "Alex",
    lastName: "Nachname (optional)",
    lastNamePlaceholder: "Wird nicht automatisch geteilt",
    lastNameHint: "Dein Nachname bleibt bei Anbieteranfragen außen vor.",
    actKind: "Du suchst für …",
    band: "Eine Band",
    bandDescription: "Auch ohne festen Bandnamen möglich.",
    solo: "Ein Solo-Projekt",
    soloDescription: "Mit Künstlernamen oder einfach mit deinem Vornamen.",
    actName: "Band- oder Künstlername (optional)",
    actNamePlaceholder: "Neon Harbour",
    preview: "So erscheinst du bei Anbietern",
    previewHint: "RoomScout verwendet genau diesen Absender. Dein Loginname wird nicht weitergegeben.",
    save: "Profil bestätigen",
    update: "Profil speichern",
    loading: "Dein Profil wird geladen …",
    error: "Das Profil konnte nicht gespeichert werden. Bitte prüfe deine Angaben und versuche es erneut.",
  },
} as const;
