// Live data states that are not represented by the scripted design preview.
export const liveScoutDe = {
  preparing: "Dein Scout macht sich bereit …",
  briefReviewAction: "Suchauftrag ansehen",
  activeStatus: "Scout unterwegs",
  pausedLabel: "Pausiert",
  chatTitle: "Mit deinem Scout schreiben",
  // Chat states, all read off the thread: the reply is on its way, is being
  // written, or the turn failed and can be sent again.
  thinking: "Dein Scout denkt nach …",
  replying: "Dein Scout antwortet gerade …",
  failed: "Antwort fehlgeschlagen.",
  retry: "Erneut senden",
  /** One line per running tool call, keyed by the tool name the Scout invoked. */
  tools: {
    rememberFact: "Merkt sich etwas",
    updateSearchDraft: "Aktualisiert deinen Suchauftrag",
    markSearchBriefReady: "Bereitet die Zusammenfassung vor",
    answerDecision: "Übernimmt deine Entscheidung",
    replyToProvider: "Schreibt dem Anbieter",
    createOutreachDraft: "Bereitet eine Anfrage vor",
    createWebformDraft: "Bereitet eine Anfrage vor",
    continueAutopilot: "Übernimmt die Anfrage",
    default: "Arbeitet …",
  },
  /** The candidate rail beside the stage: one row per laufendes Gespräch. */
  candidatesTitle: "Kandidaten",
  candidatesEmpty: "Noch keine Kandidaten. Ich melde mich, sobald ich Räume anfrage.",
  /** What a candidate row is waiting on, in the musician's words. */
  candidateState: {
    question: "Frage an dich",
    offer: "Angebot liegt vor",
    reply: "Antwort da",
    asked: "angefragt",
  },
  /** The brief, permanently beside the stage instead of behind a toggle. */
  asideTitle: "Euer Suchauftrag",
  asideEdit: "Bearbeiten",
  radius: "{count} km Umkreis",
  /** The Entscheidung answered on the stage, next to its options. */
  decisionWrite: "Oder lieber schreiben",
  decisionReviewOffer: "Angebot prüfen",
  decisionOpenChat: "Im Chat ansehen",
  /** Below 1100px the two side columns move into sheets. */
  openCandidates: "Kandidaten",
  openBrief: "Suchauftrag",
  error: "Dieser Schritt hat gerade nicht geklappt. Dein Suchauftrag bleibt gespeichert. Versuche es erneut.",
  intro: "Erzählt mir von eurer Band und dem Raum, den ihr sucht. Ich halte fest, was euch wichtig ist.",
  introKnown: "Ich habe euren Musik-Kontext gespeichert. Was für einen Proberaum sucht ihr jetzt?",
  ready: "Euer Suchauftrag ist bereit. Schaut ihn euch an und schickt mich los, wenn alles passt.",
  working: "Ich kümmere mich darum.",
  workingDetail: "Ich suche passende Räume und kläre offene Punkte mit den Anbietern. Ich melde mich, wenn ich euch brauche.",
  sending: "Ich sende eure Anfrage.",
  waiting: "Ich habe angefragt und warte auf die Antwort.",
  reply: "Der Anbieter hat geantwortet.",
  replyDetail: "Ich prüfe die Antwort und kläre, was noch offen ist.",
  offer: "Ein Raum, der zu euch passt.",
  offerDetail: "Die offenen Punkte sind geklärt. Schaut euch das Angebot an.",
  paused: "Eure Suche macht eine Pause.",
  pausedDetail: "Euer Suchauftrag bleibt gespeichert. Macht weiter, wenn ihr bereit seid.",
  complete: "Eure Zusage ist angekommen.",
  completeDetail: "Ich habe eure freigegebene Zusage gesendet. Eure Suche ist pausiert.",
  blocked: "Hier brauche ich kurz deine Hilfe.",
  blockedDetail: "Ein Schritt konnte noch nicht abgeschlossen werden. Öffne die Einstellungen oder schreib mir, damit wir weitermachen können.",
  decisionEyebrow: "Entscheidung",
  decisionYes: "Ja, so senden",
  decisionNo: "Nein, anders",
  decisionReview: "Angebot prüfen",
  decisionNotThis: "Nicht dieses",
  decisionOpenRun: "Im Browser weitermachen",
  decisionReconnect: "Verbindung neu registrieren",
  decisionAnswered: "Danke, ich mache weiter.",
  decisionTypeHint: "Oder schreib mir unten deine Antwort.",
  decisionScopes: "Betroffene Angaben",
  decisionMessage: "So würde ich schreiben:",
  changed: "Der Suchauftrag hat sich geändert. Ich prüfe das Angebot erneut.",
  offerLabel: "Angebot eingegangen",
  interimLabel: "Zwischenstand",
  clarifying: "Ich kläre noch:",
  offerFallback: "Euer Proberaum",
  priceUnknown: "Preis noch zu klären",
  perMonth: "/ Monat",
  allIn: "inklusive aller bestätigten laufenden Kosten",
  extrasUnknown: "Weitere Kosten sind noch zu klären",
  terms: "Alle Konditionen",
  noPhoto: "Kein Foto vom Anbieter vorhanden",
  review: "Angebot prüfen",
  offerNote: "Vor einer Zusage prüfst du die Konditionen und die Nachricht an den Anbieter.",
  pendingAcceptance: "Eine Zusage in diesem Gespräch wird noch zugestellt. Den genauen Stand findest du im Nachrichtenverlauf.",
  unknownAcceptance: "Die Zusage wurde möglicherweise gesendet, aber der Versandbeleg fehlt noch. Prüfe den Nachrichtenverlauf; RoomScout sendet nicht automatisch erneut.",
  failedAcceptance: "Die Zusage ist nicht als gesendet bestätigt. Bitte prüfe den Verlauf.",
  viewMessages: "Nachrichten ansehen",
  openQuestions: "Noch offen",
  editBrief: "Noch etwas ändern",
  activate: "Scout losschicken",
  activating: "Scout startet …",
  activateNote: "Ich suche und frage selbstständig an. Eine verbindliche Zusage gebt nur ihr.",
  location: "Ort",
  arrangement: "Raum",
  budget: "Budget",
  schedule: "Zeit",
  requirements: "Wichtig für euch",
  sharing: "Raum teilen",
  music: "Musik",
  instruments: "Instrumente",
  connections: "Bands kennenlernen",
  permanent: "Eigener Raum",
  shared: "Geteilter Raum",
  hourly: "Stundenweise",
  sharingYes: "Teilen ist möglich",
  sharingNo: "Nur für eure Band",
  connectionsYes: "Offen für andere Bands",
  connectionsNo: "Nur Raumsuche",
} as const;
