// Live data states that are not represented by the scripted design preview.
export const liveScoutDe = {
  preparing: "Dein Scout macht sich bereit …",
  briefReviewAction: "Suchauftrag ansehen",
  activeStatus: "Scout unterwegs",
  pausedLabel: "Pausiert",
  chatTitle: "Mit deinem Scout schreiben",
  chat: {
    composer: "Nachricht an deinen Scout …",
    empty: "Beginne ein Gespräch mit deinem Scout.",
    history: "Ältere Nachrichten laden",
    historyBusy: "Ältere Nachrichten werden geladen …",
    loadError: "Ältere Nachrichten konnten nicht geladen werden.",
    restoreDraft: "Fehlgeschlagenen Entwurf wiederherstellen",
    scout: "Dein Scout",
    send: "Senden",
    sendError: "Die Nachricht konnte nicht gesendet werden.",
    sending: "Nachricht wird gesendet …",
    status: "Gesprächsstatus",
    system: "System",
    user: "Du",
    voice: "Mit Scout sprechen",
    region: "Scout-Chat",
    transcript: "Nachrichtenverlauf",
  },
  voice: {
    cancel: "Verbindungsaufbau abbrechen",
    connect: "Gespräch starten",
    connecting: "Gespräch wird verbunden …",
    controls: "Gesprächssteuerung",
    end: "Gespräch beenden",
    error: "Verbindung unterbrochen",
    interrupt: "Scout unterbrechen",
    listening: "Ich höre zu",
    microphoneOff: "Mikrofon ausschalten",
    microphoneOn: "Mikrofon einschalten",
    reconnect: "Gespräch erneut starten",
    scout: "Dein Scout",
    speaking: "Dein Scout spricht",
    status: "Bereit, wenn du es bist",
    switchToText: "Zum Schreiben wechseln",
    thinking: "Ich denke kurz nach",
    user: "Du",
    title: "Erzähl mir, was ihr sucht.",
    region: "Gespräch mit deinem RoomScout",
    transcript: "Letzte Gesprächsbeiträge",
    muted: "Mikrofon aus",
    updating: "Dein Suchauftrag wird aktualisiert …",
    queued: "Deine Nachricht wartet kurz …",
    outcomeUnknown: "Der letzte Schritt wird noch geprüft.",
    ongoingCall: "Gespräch läuft",
    returnToScout: "Zum Scout zurückkehren",
  },
  editBudget: "Budget bearbeiten",
  editSchedule: "Zeiten bearbeiten",
  saveChanges: "Änderungen speichern",
  cancelChanges: "Änderungen verwerfen",
  budgetLabel: "Maximales Budget pro Monat",
  scheduleLabel: "Probezeiten",
  requestPending: "Wird gespeichert …",
  factUpdated: "Gespeichert: {value}",
  editCriterion: "{category} bearbeiten",
  factCategories: {
    ort: "Ort",
    budget: "Budget",
    band: "Band",
    zeit: "Zeit",
    equip: "Wichtig für euch",
  },
  // Chat states, all read off the thread: the reply is on its way, is being
  // written, or the turn failed and can be sent again.
  thinking: "Dein Scout denkt nach …",
  /** Accessible name of the scroller's "jump to the newest message" button. */
  scrollToEnd: "Zu den neuesten Nachrichten",
  /**
   * What the Marker says while the Scout works and has not written a word yet.
   * One is picked at random per turn and they rotate every ~2.2 s, so a long
   * wait reads as somebody thinking rather than as a frozen line. The order is
   * the rotation order — `src/ui/chat/thinkingVerbs.ts` holds the key list.
   */
  thinkingVerbs: {
    sorting: "Sortiert Gedanken …",
    brief: "Blättert im Suchauftrag …",
    weighing: "Wägt Optionen ab …",
    writing: "Formuliert …",
    listening: "Hört noch mal genau hin …",
    checking: "Prüft die Details …",
  },
  /** @deprecated The composer no longer says why it waits — the Marker does. */
  replying: "Dein Scout antwortet gerade …",
  failed: "Antwort fehlgeschlagen.",
  retry: "Erneut senden",
  /** One line per running tool call, keyed by the tool name the Scout invoked. */
  tools: {
    rememberFact: "Merkt sich etwas",
    updateSearchDraft: "Aktualisiert deinen Suchauftrag",
    markSearchBriefReady: "Bereitet die Zusammenfassung vor",
    answerDecision: "Übernimmt deine Entscheidung",
    replyToProvider: "Schreibt dem Anbieter",
    createOutreachDraft: "Bereitet eine Anfrage vor",
    createWebformDraft: "Bereitet eine Anfrage vor",
    continueAutopilot: "Übernimmt die Anfrage",
    default: "Arbeitet …",
  },
  /** The candidate rail beside the stage: one row per laufendes Gespräch. */
  candidatesTitle: "Kandidaten",
  candidatesEmpty: "Noch keine Kandidaten. Ich melde mich, sobald ich Räume anfrage.",
  /** What a candidate row is waiting on, in the musician's words. */
  candidateState: {
    question: "Frage an dich",
    offer: "Angebot liegt vor",
    reply: "Antwort da",
    asked: "angefragt",
  },
  /** The brief, permanently beside the stage instead of behind a toggle. */
  asideTitle: "Euer Suchauftrag",
  asideEdit: "Bearbeiten",
  radius: "{count} km Umkreis",
  budgetValue: "Bis {count} € / Monat",
  /** The band in one line: „4er-Rockband“ instead of „4“ neben „Rock“. */
  bandProfile: "{count}er-{text}band",
  /** A fact the Scout noted but has not confirmed yet. */
  factUnsure: "{text} · noch zu klären",
  /**
   * Facets — the Scout stores `namespace`/`key` freely, and only the ones
   * listed here are shown. `src/features/scout/viewModel.ts` holds the map from
   * namespace/key to these strings; a facet without an entry stays out of the
   * brief instead of appearing as a raw key.
   */
  facets: {
    bandSize: "{count} Personen",
    equipmentStorage: "Lagerplatz für eigenes Equipment",
    equipmentDrums: "Schlagzeug vorhanden",
    equipmentPa: "PA vorhanden",
    equipmentBackline: "Backline vorhanden",
    accessParking: "Parkplatz vorhanden",
    accessTransport: "Erreichbar mit {text}",
    accessAnytime: "Rund um die Uhr zugänglich",
    noiseNight: "Abends und nachts spielen erlaubt",
    roomSize: "{count} m²",
    contractMinTerm: "Mindestlaufzeit {count} Monate",
    costDeposit: "Kaution {count} €",
  },
  /** The Entscheidung answered on the stage, next to its options. */
  decisionWrite: "Oder lieber schreiben",
  decisionOfferQuestion: "Ein Angebot liegt vor. Willst du es prüfen?",
  decisionReviewOffer: "Angebot prüfen",
  decisionOpenChat: "Im Chat ansehen",
  /** Below 1100px the two side columns move into sheets. */
  openCandidates: "Kandidaten",
  openBrief: "Suchauftrag",
  error: "Dieser Schritt hat gerade nicht geklappt. Dein Suchauftrag bleibt gespeichert. Versuche es erneut.",
  intro: "Erzählt mir von eurer Band und dem Raum, den ihr sucht. Ich halte fest, was euch wichtig ist.",
  introKnown: "Ich habe euren Musik-Kontext gespeichert. Was für einen Proberaum sucht ihr jetzt?",
  ready: "Euer Suchauftrag ist bereit. Schaut ihn euch an und schickt mich los, wenn alles passt.",
  working: "Ich kümmere mich darum.",
  workingDetail: "Ich suche passende Räume und kläre offene Punkte mit den Anbietern. Ich melde mich, wenn ich euch brauche.",
  sending: "Ich sende eure Anfrage.",
  waiting: "Ich habe angefragt und warte auf die Antwort.",
  reply: "Der Anbieter hat geantwortet.",
  replyDetail: "Ich prüfe die Antwort und kläre, was noch offen ist.",
  offer: "Ein Raum, der zu euch passt.",
  offerDetail: "Die offenen Punkte sind geklärt. Schaut euch das Angebot an.",
  paused: "Eure Suche macht eine Pause.",
  pausedDetail: "Euer Suchauftrag bleibt gespeichert. Macht weiter, wenn ihr bereit seid.",
  complete: "Eure Zusage ist angekommen.",
  completeDetail: "Ich habe eure freigegebene Zusage gesendet. Eure Suche ist pausiert.",
  blocked: "Hier brauche ich kurz deine Hilfe.",
  blockedDetail: "Ein Schritt konnte noch nicht abgeschlossen werden. Öffne die Einstellungen oder schreib mir, damit wir weitermachen können.",
  decisionEyebrow: "Entscheidung",
  decisionYes: "Ja, so senden",
  decisionNo: "Nein, anders",
  decisionReview: "Angebot prüfen",
  decisionNotThis: "Nicht dieses",
  decisionOpenRun: "Im Browser weitermachen",
  decisionReconnect: "Verbindung neu registrieren",
  decisionAnswered: "Danke, ich mache weiter.",
  /** The Entscheidung's own free-text field — never the chat composer. */
  decisionOwnLabel: "Eigene Antwort",
  decisionChangeLabel: "Was soll anders sein?",
  decisionInstructionHint: "Das liest dein Scout, der Anbieter bekommt es nicht zu sehen.",
  decisionSubmit: "Antworten",
  decisionRequired: "Wähl eine Antwort oder schreib deine eigene.",
  decisionScopes: "Betroffene Angaben",
  decisionMessage: "So würde ich schreiben:",
  changed: "Der Suchauftrag hat sich geändert. Ich prüfe das Angebot erneut.",
  offerLabel: "Angebot eingegangen",
  interimLabel: "Zwischenstand",
  clarifying: "Ich kläre noch:",
  offerFallback: "Euer Proberaum",
  priceUnknown: "Preis noch zu klären",
  perMonth: "/ Monat",
  allIn: "inklusive aller bestätigten laufenden Kosten",
  extrasUnknown: "Weitere Kosten sind noch zu klären",
  terms: "Alle Konditionen",
  noPhoto: "Kein Foto vom Anbieter vorhanden",
  review: "Angebot prüfen",
  offerNote: "Vor einer Zusage prüfst du die Konditionen und die Nachricht an den Anbieter.",
  /**
   * The four states of a Zusage, in the musician's words. They are precise on
   * purpose: „möglicherweise gesendet“ is not a state anybody can act on.
   * `unknownAcceptance` covers the first three minutes after the request moved,
   * `unconfirmedAcceptance` everything after that.
   */
  pendingAcceptance: "Zusage wird gesendet …",
  unknownAcceptance: "Versand wird bestätigt …",
  unconfirmedAcceptance: "Der Versand ist nicht bestätigt. Prüfe den Verlauf.",
  failedAcceptance: "Die Zusage konnte nicht gesendet werden. Prüfe den Verlauf.",
  sentAcceptance: "Zusage gesendet · {time}",
  acceptance: {
    changed: "Das Angebot oder die Nachricht hat sich geändert. Es wurde nichts gesendet. Schließe diese Prüfung und beginne erneut mit dem aktuellen Angebot.",
    expired: "Diese Freigabe ist abgelaufen. Es wurde nichts gesendet.",
    approveError: "Die Annahme konnte nicht freigegeben werden. Es wurde nichts gesendet.",
    prepareError: "Die Annahme konnte nicht vorbereitet werden. Es wurde nichts gesendet.",
    title: "Angebot verbindlich annehmen",
    description: "Prüfe Empfänger, Absender und Nachricht genau. Erst nach deiner Freigabe darf RoomScout diese Annahme einmal senden.",
    loading: "Die genaue Annahme wird vorbereitet …",
    unavailable: "Diese Annahme ist nicht verfügbar. Es wurde nichts gesendet.",
    stale: "Diese Prüfung ist nicht mehr aktuell, weil sich Angebot, Suche oder Gespräch geändert haben. Es wurde nichts gesendet.",
    failed: "Die Annahme ist fehlgeschlagen und wurde nicht als gesendet bestätigt. Diese genaue Anfrage kann nicht erneut freigegeben werden.",
    pending: "Annahme freigegeben. Die Zustellung wird noch geprüft; das bestätigt noch keinen Versand.",
    sent: "Annahme gesendet.",
    termsRegion: "Angenommene Angebotsbedingungen",
    termsTitle: "Dieses Angebot wird angenommen",
    monthlyTotal: "Monatlich gesamt",
    priceUnconfirmed: "Nicht bestätigt",
    allCostsKnown: "Alle laufenden Kosten genannt",
    costsMayRemain: "Weitere Kosten können noch offen sein",
    messageRegion: "Genaue Nachricht",
    sender: "Absender",
    recipient: "Empfänger",
    subject: "Betreff",
    noSubject: "(Kein Betreff)",
    exactMessage: "Genaue Nachricht",
    disclosure: "RoomScout sendet nur diese geprüfte Plattformnachricht an roomscout.dev. Damit wird kein Vertrag unterschrieben, kein Raum gebucht und keine Zahlung ausgelöst.",
    acknowledgement: "Ich habe diese genauen Bedingungen, Absender, Empfänger, Betreff und Nachricht geprüft. RoomScout darf diese Annahme einmal senden.",
    cancel: "Abbrechen",
    approving: "Wird freigegeben …",
    approve: "Freigeben und Annahme senden",
  },
  viewMessages: "Nachrichten ansehen",
  openQuestions: "Noch offen",
  editBrief: "Noch etwas ändern",
  activate: "Scout losschicken",
  activating: "Scout startet …",
  activateNote: "Ich suche und frage selbstständig an. Eine verbindliche Zusage gebt nur ihr.",
  location: "Ort",
  /** The one fact that carries Raumform, Bandgröße, Genre und Instrumente. */
  band: "Band",
  arrangement: "Raum",
  budget: "Budget",
  schedule: "Zeit",
  requirements: "Wichtig für euch",
  sharing: "Raum teilen",
  music: "Musik",
  instruments: "Instrumente",
  connections: "Bands kennenlernen",
  permanent: "Eigener Raum",
  shared: "Geteilter Raum",
  hourly: "Stundenweise",
  sharingYes: "Teilen ist möglich",
  sharingNo: "Nur für eure Band",
  connectionsYes: "Offen für andere Bands",
  connectionsNo: "Nur Raumsuche",
} as const;
