export const liveOperatorCopy = {
  accessChecking: "Betreiberzugang wird geprüft …",
  accessDenied: "Betreiberzugang erforderlich",
  title: "Betreiberansicht",
  operations: "Betrieb",
  environment: "Interner Betrieb",
  avatarInitials: "OP",
  avatarLabel: "Operator",
  footer: "Interne Betriebsansicht · Live-Daten",
  overview: "Übersicht",
  sources: "Quellen",
  tasks: "Aufträge",
  integrations: "Integrationen",
  flags: "Feature-Flags",
  diag: "Diagnose",
  overviewTitle: "Betrieb im Blick",
  overviewSubtitle: "Provider, Quellen und wartende Aufgaben.",
  sourcesTitle: "Quellen",
  sourcesSubtitle: "Technischer Zugang zu den beobachteten Quellen.",
  tasksTitle: "Aufträge",
  tasksSubtitle: "Aktuelle Betriebsereignisse und Vorgänge.",
  integrationsTitle: "Integrationen",
  integrationsSubtitle: "Konfiguration der externen Dienste.",
  flagsTitle: "Feature-Flags",
  flagsSubtitle: "Schalter für kontrollierte Produktfunktionen.",
  diagTitle: "Diagnose",
  diagSubtitle: "Ereignisse und Konfigurationsfehler nachvollziehen.",
  subtitle: "Live-Zustand der laufenden RoomScout-Dienste.",
  tools: "Werkzeuge",
  advancedTools: "Erweiterte Werkzeuge",
  refresh: "Konfiguration neu prüfen",
  refreshing: "Konfiguration wird geprüft …",
  bounded: "Begrenzte Live-Stichprobe",
  liveMetrics: "Live-Kennzahlen",
  attention: "Bereiche mit Handlungsbedarf: {count}",
  noAttention: "Keine Auffälligkeiten in der aktuellen Stichprobe.",
  viewTasks: "Aufträge ansehen",
  viewFlags: "Flags ansehen",
  activitySummary: "Ereignisse in der aktuellen Stichprobe: {count}",
  noActivity: "Noch keine Betriebsereignisse vorhanden.",
  noDiagnostics: "Keine Diagnoseereignisse in der aktuellen Stichprobe.",
  recentEvents: "Ereignisfolge",
  allTasks: "Alle",
  attentionOnly: "Braucht Aufmerksamkeit",
  noAttentionTasks: "Keine auffälligen Vorgänge in der aktuellen Stichprobe.",
  providerCheckOnly: "Nur Konfigurationsprüfung, kein Live-Test",
  configured: "Konfiguriert",
  notChecked: "Noch nicht geprüft",
  incomplete: "Unvollständig",
  disabled: "Deaktiviert",
  clientOnly: "Nur im Client prüfbar",
  checkFailed:
    "Die Konfigurationsprüfung ist fehlgeschlagen. Bitte erneut versuchen.",
  checkComplete: "Konfigurationsprüfung abgeschlossen.",
  configuration: "Konfiguration:",
  health: "Betriebszustand:",
  healthUnknown: "Nicht live geprüft",
  configuredNotHealthy:
    "Konfiguriert bedeutet nicht automatisch erreichbar oder gesund. Diese Prüfung liest nur die vorhandene Konfiguration.",
  sourcesLoading: "Quellen werden geladen …",
  noSources: "Keine Quellen im aktuellen Live-Ergebnis.",
  sourcesReadOnly:
    "Diese Tabelle ist schreibgeschützt. Änderungen bleiben im bestehenden Quellenwerkzeug.",
  unknown: "Nicht angegeben",
  neverChecked: "Noch nicht geprüft",
  openSources: "Quellen und Monitoring öffnen",
  sourceColumns: {
    source: "Quelle",
    region: "Region",
    connection: "Anbindung",
    lastCheck: "Letzter Check",
  },
  flagsUnavailable:
    "Die Schalter sind noch nicht an die Live-Einstellungen angebunden.",
  flagsLimitation:
    "Deshalb zeigt diese Ansicht keine vermuteten Schalterstände und kann keine Änderungen speichern.",
  saveFlags: "Änderungen speichern",
  unknownState: "Unbekannt",
  flagRows: {
    voice: {
      label: "Voice Scout",
      effect: "Steuert den Zugang zum sprachbasierten Scout.",
    },
    publicSearch: {
      label: "Öffentliche Quellensuche",
      effect: "Steuert die Suche in freigegebenen öffentlichen Quellen.",
    },
  },
  taskColumns: {
    process: "Vorgang",
    source: "Quelle",
    status: "Status",
    next: "Nächster Schritt",
  },
  unavailableDash: "—",
  details: "Details",
  diagLimitation:
    "Die Diagnose zeigt die begrenzte Ereignisstichprobe und Konfigurationsfehler; sie führt keinen eigenständigen Dienstetest aus.",
  openSignals: "Signal-Warteschlange öffnen",
  openOutreach: "Freigaben und Versand öffnen",
  openAudit: "Audit-Protokoll öffnen",
  open: "Öffnen",
  toolLabels: {
    sources: "Quellen und Monitoring",
    signals: "Signal-Warteschlange",
    outreach: "Freigaben und Versand",
    inbox: "Scout-Postfach",
    audit: "Audit-Protokoll",
  },
  metrics: {
    publishedSignals: "Veröffentlichte Signale",
    staleSignals: "Veraltete Signale",
    detailBacklog: "Detail-Warteschlange",
    detailFailures: "Fehlgeschlagene Details",
    awaitingApproval: "Ausstehende Freigaben",
    repliedThreads: "Antworten",
    unhealthySources: "Gestörte Quellen",
    activeVoiceSessions: "Aktive Sprachsitzungen",
    activeMailboxes: "Aktive Scout-Postfächer",
  },
  providers: {
    convexAiGateway: "Convex AI Gateway",
    firecrawl: "Firecrawl",
    agentmail: "AgentMail",
    browserbase: "Browserbase",
    mapbox: "Mapbox",
    openaiDirect: "OpenAI direkt",
  },
  providerRoles: {
    convexAiGateway: "Text & Auswertung",
    firecrawl: "Quellen beobachten",
    agentmail: "Scout-Postfächer",
    browserbase: "Portal-Zugänge",
    mapbox: "Karten und Geocoding",
    openaiDirect: "Voice & Embeddings",
  },
} as const;
