export const liveSettingsCopy = {
  autoSourcesFixed: "Die automatische Quellenauswahl ist derzeit fest aktiviert. Einzelne Quellen kannst du unten ausschließen.",
  noSourcesYet: "Noch keine Quellen für diese Suche eingerichtet.",
  noMoreSources: "Aktuell sind keine weiteren Portal-Verbindungen verfügbar.",
  connectionScope: "Hier verwaltest du den Portalzugang für Nachrichten und Antworten. Die Quellenauswahl für diese Suche bleibt davon getrennt.",
  saved: "Gespeichert.",
  actionFailed: "Die Aktion konnte nicht abgeschlossen werden.",
  synced: "Portal-Postfach synchronisiert.",
  registrationStarted: "Sichere Scout-Registrierung gestartet.",
  authenticationStarted: "Sichere Anmeldung gestartet.",
  connectionAdded: "Portal-Verbindung hinzugefügt.",
  connectionPaused: "Portal-Verbindung pausiert.",
  connectionRemoved: "Portal-Verbindung und Browser-Kontext entfernt.",
  mailboxReady: "Scout-Adresse ist eingerichtet.",
  personalArea: "Persönlicher Bereich",
  discardTitle: "Ungespeicherte Änderungen",
  discardDescription: "Deine Änderungen wurden noch nicht gespeichert.",
  keepEditing: "Weiter bearbeiten",
  discard: "Verwerfen",
  discardBody: "Beim Verlassen gehen die Änderungen verloren.",
  removeTitle: "Portal-Verbindung entfernen?",
  removeDescription: "Der gespeicherte Browser-Kontext wird gelöscht; das Konto beim Anbieter bleibt bestehen.",
  keepConnected: "Verbunden lassen",
  removeConnection: "Verbindung entfernen",
  removeBody: "Scout verwendet dieses Portal danach nicht mehr.",
  sourcesTitle: "Quellen & Zugänge",
  sourcesForCity: "Quellen für eure Suche in {city}.",
  sourcesNoNeed: "Verbinde zuerst einen Suchauftrag mit Scout.",
  includeSource: "{name} einbeziehen",
  portalConnections: "Portal-Verbindungen",
  portalStatusActive: "Aktiv",
  portalStatusNeedsAuth: "Anmeldung erforderlich",
  portalStatusReauthRequired: "Erneute Anmeldung erforderlich",
  portalStatusPaused: "Pausiert",
  portalStatusDisabled: "Deaktiviert",
  portalStatusUnknown: "Status unbekannt",
  portalPolicyAllowed: "Nutzung freigegeben",
  portalPolicyBlocked: "Nutzung nicht freigegeben",
  portalPolicyUnknown: "Freigabe ungeklärt",
  syncInbox: "Postfach synchronisieren",
  pause: "Pausieren",
  authenticate: "Sicher anmelden",
  registerScout: "Scout registrieren lassen",
  recoverFirecrawlProfile: "Gespeichertes Profil prüfen",
  viewRegistrationProgress: "Fortschritt ansehen",
  firecrawlManualLoginUnsupported: "Manuelle Anmeldung ist für Firecrawl hier nicht verfügbar.",
  registrationQueued: "Registrierung wartet",
  registrationOpening: "Registrierung wird geöffnet",
  registrationWaitingVerification: "Bestätigungsmail wird erwartet",
  registrationSubmittingVerification: "Bestätigungscode wird geprüft",
  registrationFailed: "Registrierung fehlgeschlagen",
  remove: "Entfernen",
  include: "Einbeziehen",
  scoutAddress: "Scout-Adresse",
  notConfigured: "Noch nicht eingerichtet",
  configureAddress: "Adresse einrichten",
  autonomyTitle: "Handlungsspielraum",
  autonomyLead: "Persistierte Freigaben für den aktuellen Suchauftrag.",
  createNeedFirst: "Erstelle zuerst mit Scout einen Suchauftrag.",
  mandateSummary: "Version {version} · bis {date} · maximal {count} Kontakte pro Tag.",
  commitmentBoundary: "Verbindliche Entscheidungen, Buchungen und Zahlungen brauchen weiterhin deine exakte Zustimmung.",
  pauseAutopilot: "Autopilot pausieren",
  reviewMode: "Mit Rücksprache",
  reviewModeBody: "Scout recherchiert erst nach deiner ausdrücklichen Freigabe. Der Standard-Autopilot erlaubt nur nicht bindende Aktionen innerhalb fester Grenzen.",
  activateAutopilot: "Standard-Autopilot aktivieren",
  modeGuided: "Mit Rücksprache",
  modeResearch: "Recherche-Autopilot",
  modeOutreach: "Kontakt-Autopilot",
  modeNegotiation: "Verhandlungs-Autopilot",
  autonomySaveFailed: "Der Handlungsspielraum konnte nicht gespeichert werden.",
  knowledgeTitle: "Was dein Scout weiß",
  noContext: "Noch kein zusammengefasster Kontext.",
  importContext: "Kontext importieren",
  retireFact: "Nicht mehr verwenden",
  changeLog: "Änderungsverlauf",
  profileTitle: "Profil",
  profileLead: "So spricht RoomScout dich in diesem privaten Arbeitsbereich an.",
  displayName: "Anzeigename",
  save: "Speichern",
  immutableLogin: "Benutzername und Anmeldung bleiben unverändert: {username}",
  notificationsTitle: "Benachrichtigungen",
  openInbox: "Postfach öffnen",
  billingTitle: "Tarif & Nutzung",
  privacyTitle: "Datenschutz",
  privacyLead: "RoomScout speichert Suchaufträge, geprüfte Erinnerungen, Freigaben und Ereignismetadaten in Convex.",
  notStored: "Rohaudio, Passwörter, 2FA-Werte, Cookies und kurzlebige Live-View-Links werden nicht gespeichert.",
  loading: "Einstellungen werden geladen …",
  unavailable: "Diese Einstellung ist noch nicht mit einem verlässlichen Dienst verbunden.",
  sourceDisclosure: "Quellen gelten nur für den ausgewählten Suchauftrag. Ausgeschlossene Quellen werden nicht verwendet.",
  notificationUnavailable: "Benachrichtigungen erscheinen derzeit nur in RoomScout. E-Mail-, Push- und Browser-Einstellungen sind noch nicht verfügbar.",
  billingUnavailable: "RoomScout hat derzeit keinen Tarif, keine Zahlungsdaten und keine belastbare nutzerbezogene Verbrauchszählung.",
  privacyUnavailable: "Datenexport und Kontolöschung sind noch nicht als sichere Self-Service-Aktionen verfügbar.",
} as const;
