export const liveSettingsCopy = {
  autoSourcesFixed: "Die automatische Quellenauswahl ist derzeit fest aktiviert. Einzelne Quellen kannst du unten ausschließen.",
  noSourcesYet: "Noch keine Quellen für diese Suche eingerichtet.",
  noMoreSources: "Aktuell sind keine weiteren Portal-Verbindungen verfügbar.",
  connectionScope: "Hier verwaltest du den Portalzugang für Nachrichten und Antworten. Die Quellenauswahl für diese Suche bleibt davon getrennt.",
  saved: "Gespeichert.",
  actionFailed: "Die Aktion konnte nicht abgeschlossen werden.",
  synced: "Portal-Postfach synchronisiert.",
  registrationStarted: "Sichere Scout-Registrierung gestartet.",
  authenticationStarted: "Sichere Anmeldung gestartet.",
  connectionAdded: "Portal-Verbindung hinzugefügt.",
  connectionPaused: "Portal-Verbindung pausiert.",
  connectionRemoved: "Portal-Verbindung und Browser-Kontext entfernt.",
  mailboxReady: "Scout-Adresse ist eingerichtet.",
  personalArea: "Persönlicher Bereich",
  discardTitle: "Ungespeicherte Änderungen",
  discardDescription: "Deine Änderungen wurden noch nicht gespeichert.",
  keepEditing: "Weiter bearbeiten",
  discard: "Verwerfen",
  discardBody: "Beim Verlassen gehen die Änderungen verloren.",
  removeTitle: "Portal-Verbindung entfernen?",
  removeDescription: "Der gespeicherte Browser-Kontext wird gelöscht; das Konto beim Anbieter bleibt bestehen.",
  keepConnected: "Verbunden lassen",
  removeConnection: "Verbindung entfernen",
  removeBody: "Scout verwendet dieses Portal danach nicht mehr.",
  sourcesTitle: "Quellen & Zugänge",
  sourcesForCity: "Quellen für eure Suche in {city}.",
  sourcesNoNeed: "Verbinde zuerst einen Suchauftrag mit Scout.",
  includeSource: "{name} einbeziehen",
  portalConnections: "Portal-Verbindungen",
  portalStatusActive: "Aktiv",
  portalStatusNeedsAuth: "Anmeldung erforderlich",
  portalStatusReauthRequired: "Erneute Anmeldung erforderlich",
  portalStatusPaused: "Pausiert",
  portalStatusDisabled: "Deaktiviert",
  portalStatusUnknown: "Status unbekannt",
  portalPolicyAllowed: "Nutzung freigegeben",
  portalPolicyBlocked: "Nutzung nicht freigegeben",
  portalPolicyUnknown: "Freigabe ungeklärt",
  syncInbox: "Postfach synchronisieren",
  pause: "Pausieren",
  authenticate: "Sicher anmelden",
  registerScout: "Scout registrieren lassen",
  recoverFirecrawlProfile: "Gespeichertes Profil prüfen",
  viewRegistrationProgress: "Fortschritt ansehen",
  firecrawlManualLoginUnsupported: "Manuelle Anmeldung ist für Firecrawl hier nicht verfügbar.",
  registrationQueued: "Registrierung wartet",
  registrationOpening: "Registrierung wird geöffnet",
  registrationWaitingVerification: "Bestätigungsmail wird erwartet",
  registrationSubmittingVerification: "Bestätigungscode wird geprüft",
  registrationFailed: "Registrierung fehlgeschlagen",
  remove: "Entfernen",
  include: "Einbeziehen",
  scoutAddress: "Scout-Adresse",
  notConfigured: "Noch nicht eingerichtet",
  configureAddress: "Adresse einrichten",
  autonomyTitle: "Handlungsspielraum",
  autonomyLead: "Persistierte Freigaben für den aktuellen Suchauftrag.",
  createNeedFirst: "Erstelle zuerst mit Scout einen Suchauftrag.",
  mandateSummary: "Version {version} · bis {date} · maximal {count} Kontakte pro Tag.",
  commitmentBoundary: "Verbindliche Entscheidungen, Buchungen und Zahlungen brauchen weiterhin deine exakte Zustimmung.",
  pauseAutopilot: "Autopilot pausieren",
  reviewMode: "Mit Rücksprache",
  reviewModeBody: "Scout recherchiert erst nach deiner ausdrücklichen Freigabe. Der Standard-Autopilot erlaubt nur nicht bindende Aktionen innerhalb fester Grenzen.",
  activateAutopilot: "Standard-Autopilot aktivieren",
  modeGuided: "Mit Rücksprache",
  modeResearch: "Recherche-Autopilot",
  modeOutreach: "Kontakt-Autopilot",
  modeNegotiation: "Verhandlungs-Autopilot",
  autonomySaveFailed: "Der Handlungsspielraum konnte nicht gespeichert werden.",
  knowledgeTitle: "Was dein Scout weiß",
  noContext: "Noch kein zusammengefasster Kontext.",
  knowledgeCategoriesAria: "Wissenskategorien",
  knowledgeEmpty: "Hier habe ich noch nichts gespeichert.",
  knowledgeNoChanges: "Noch keine Änderungen.",
  knowledgeSourceConversation: "Aus dem Gespräch",
  knowledgeSourceImport: "Aus importiertem Kontext",
  knowledgeSourceUserEdit: "Von euch bearbeitet",
  knowledgeSourceAgentMail: "Aus einer Scout-Nachricht",
  knowledgeSourceObserved: "Vom Scout beobachtet",
  knowledgeSourceSavedNeed: "Teil eures aktuellen Suchauftrags",
  knowledgeSavedNeedSubject: "Euer Suchauftrag",
  knowledgeNoSharing: "Keine Raumteilung",
  knowledgeSharingOpen: "Raumteilung möglich",
  knowledgePeople: "{count} Personen",
  knowledgeGenreJoiner: " und ",
  knowledgeRadius: "{count} km Umkreis",
  knowledgeBudget: "Bis {value} € / Monat",
  knowledgeLoudPaRequirement: "Laute Proben mit PA erforderlich",
  importContext: "Kontext importieren",
  retireFact: "Nicht mehr verwenden",
  changeLog: "Änderungsverlauf",
  profileTitle: "Profil",
  profileLead: "Lege fest, wen dein Scout vertritt und wie RoomScout dich bei Anbietern vorstellt.",
  displayName: "Anzeigename",
  save: "Speichern",
  immutableLogin: "Benutzername und Anmeldung bleiben unverändert: {username}",
  notificationsTitle: "Benachrichtigungen",
  openInbox: "Postfach öffnen",
  billingTitle: "Tarif & Nutzung",
  privacyTitle: "Datenschutz",
  privacyLead: "RoomScout speichert Suchaufträge, geprüfte Erinnerungen, Freigaben und Ereignismetadaten in Convex.",
  notStored: "Rohaudio, Passwörter, 2FA-Werte, Cookies und kurzlebige Live-View-Links werden nicht gespeichert.",
  loading: "Einstellungen werden geladen …",
  unavailable: "Diese Einstellung ist noch nicht mit einem verlässlichen Dienst verbunden.",
  sourceDisclosure: "Quellen gelten nur für den ausgewählten Suchauftrag. Ausgeschlossene Quellen werden nicht verwendet.",
  notificationUnavailable: "Benachrichtigungen erscheinen derzeit nur in RoomScout. E-Mail-, Push- und Browser-Einstellungen sind noch nicht verfügbar.",
  billingUnavailable: "RoomScout hat derzeit keinen Tarif, keine Zahlungsdaten und keine belastbare nutzerbezogene Verbrauchszählung.",
  billingAccess: "Dein Zugang",
  billingDemoAccess: "Demo-Zugang",
  billingNoSubscription: "Kein kostenpflichtiges Abonnement aktiv.",
  billingViewPlans: "Tarife ansehen",
  billingActivity: "Aktivität",
  billingNotTracked: "Noch nicht erfasst",
  billingActiveSearches: "Aktive Suchen",
  billingProvidersContacted: "Anbieter kontaktiert",
  billingScoutConversations: "Gespräche mit Scout",
  billingActivityFootnote: "Aktivitätsübersicht, keine Abrechnungseinheiten.",
  billingPaymentTitle: "Zahlungsdaten",
  billingPaymentDetail: "Keine Zahlungsmethode hinterlegt",
  billingManage: "Verwalten",
  billingAddressTitle: "Rechnungsadresse",
  billingAddressDetail: "Noch nicht hinterlegt",
  billingAdd: "Hinzufügen",
  billingInvoices: "Rechnungen",
  billingNoInvoices: "Noch keine Rechnungen",
  billingReceiptsLater: "Hier findest du später deine Belege.",
  billingNoIntegration: "Noch keine Zahlungsintegration",
  privacyUnavailable: "Datenexport und Kontolöschung sind noch nicht als sichere Self-Service-Aktionen verfügbar.",
  privacyDataTitle: "Deine Daten, deine Kontrolle",
  privacyDataLead: "Hier siehst du, welche Informationen RoomScout für deine Suche in der Cloud speichert und wo du sie verwalten kannst.",
  privacyStoredTitle: "Gespeicherte Angaben",
  privacyStoredFallback: "Angaben über eure Band und Suche",
  privacyStoredOne: "{count} Angabe über euch und eure Suche",
  privacyStoredMany: "{count} Angaben über euch und eure Suche",
  privacyViewStored: "Gespeicherte Angaben ansehen",
  privacyTranscriptTitle: "Gesprächsverlauf",
  privacyTranscriptDetail: "Eure Gespräche mit dem Scout sind in der App einsehbar.",
  privacyViewTranscript: "Gespräche ansehen",
  privacyPortalsTitle: "Portalzugänge",
  privacyPortalsFallback: "Verbindungen zu euren Portalen",
  privacyPortalsOne: "{count} verbundener Portalzugang",
  privacyPortalsMany: "{count} verbundene Portalzugänge",
  privacyManagePortals: "Portalzugänge verwalten",
  privacyExportTitle: "Export",
  privacyExportDetail: "Ein sicherer Self-Service-Datenexport ist noch nicht verfügbar.",
  privacyExport: "Daten exportieren",
  privacyDeleteTitle: "Konto löschen",
  privacyDeleteDetail: "Die endgültige Löschung aller Kontodaten ist noch nicht als sichere Self-Service-Aktion verfügbar.",
  privacyDelete: "Konto löschen",
  privacyVendorsTitle: "Beteiligte Dienstleister",
  privacyVendorsDetail: "RoomScout nutzt je nach Funktion Convex, OpenAI, Firecrawl, AgentMail und Browserbase für Datenspeicherung, KI-Verarbeitung, Webrecherche, Scout-Postfächer und Portalzugänge.",
  importDialogTitle: "Musik-Kontext importieren",
  importCollectDescription: "Nützlichen Kontext übernehmen. Die Kontrolle behalten.",
  importReviewDescription: { one: "1 von {n} ausgewählt", other: "{count} von {n} ausgewählt" },
  importAnalyze: "Zur Prüfung analysieren",
  importBack: "Zurück",
  importRemember: { one: "1 Angabe übernehmen", other: "{count} Angaben übernehmen" },
  importStepAsk: "01 · Deinen bisherigen Assistenten fragen",
  importAskBody: "Kopiere diesen Prompt in ChatGPT, Claude oder einen anderen Assistenten, der dein Musikleben bereits kennt.",
  importPrompt: "Ich richte RoomScout ein, einen Assistenten, der Musikerinnen, Musikern und Bands hilft, Proberäume und passende Partner für eine Raumteilung zu finden. Erstelle ausschließlich auf Grundlage dessen, was ich dir in früheren Gesprächen ausdrücklich erzählt habe, einen knappen Kontext-Export über mein Musikleben. Nenne nützliche Fakten zu Bands, Projekten, Mitgliedern, Rollen, Instrumenten, Musikrichtung, Arbeitsweise, Proben, Zeiten, Orten, Mobilität, Ausstattung, Lagerung, Lautstärke, Zugang, Budget, Raumwünschen, Ausschlusskriterien, Offenheit für Raumteilung, aktuellen Zielen und offenen Fragen. Trenne klar zwischen mir, anderen Personen und Bands. Kennzeichne unsichere oder veraltete Angaben. Rate nicht. Lass Passwörter, Anmeldedaten, Finanzkontodaten, Gesundheitsinformationen, genaue Privatadressen, private Kontaktdaten und sachfremde persönliche Informationen weg. Antworte als Klartext mit eindeutigen Überschriften und Aufzählungspunkten. Ich prüfe das Ergebnis, bevor RoomScout daraus Angaben speichert.",
  importCopyPrompt: "Prompt kopieren",
  importCopied: "Kopiert",
  importStepPaste: "02 · Ergebnis hier einfügen",
  importPasteBody: "RoomScout extrahiert mögliche Angaben über das AI Gateway. Gespeichert wird erst, nachdem du sie geprüft und bestätigt hast.",
  importSourceLabel: "Externer Assistenz-Kontext",
  importSourcePlaceholder: "Exportierten Musik-Kontext einfügen …",
  importScoutReadout: "Scout-Auswertung",
  importReviewMeta: { one: "Vorschläge: 1 · Entitäten: {n} · der Rohtext wird nicht gespeichert", other: "Vorschläge: {count} · Entitäten: {n} · der Rohtext wird nicht gespeichert" },
  importCategoryIdentity: "Identität",
  importCategoryMusic: "Musik",
  importCategoryLocation: "Ort",
  importCategoryMobility: "Mobilität",
  importCategorySchedule: "Zeitplan",
  importCategoryEquipment: "Ausstattung",
  importCategoryGoal: "Ziel",
  importCategoryPreference: "Präferenz",
  importCategoryConstraint: "Bedingung",
  importCategoryRelationship: "Beziehung",
  importCategoryCollaboration: "Zusammenarbeit",
  importCategoryRoomNeed: "Raumbedarf",
  importCategoryOther: "Sonstiges",
  importSensitivityPersonal: "persönlich",
  importSensitivitySensitive: "sensibel",
  importError: "Der Kontext konnte nicht verarbeitet werden. Bitte versuche es erneut.",
} as const;
